### ISSUE TITLE
12.41 dump issues

### ISSUE THREAD

**Issue by mlodyskiny** [Encryqed/Dumper-7#10]
12.41 dump aint compiling, class redefinition in files that start with s12 and intro files
getsocketlocation func in mesh crashes my game (uworld is good, i use the initgobjects func before everything)

**Comment by Fischsalat** [comment]
@Encryqed

**Comment by 0ez** [comment]
yeah ik its experimental lol. lmk when the issue is fixed gotta fix my paste

**Comment by 0ez** [comment]
![image](https://user-images.githubusercontent.com/69488850/220678179-757e1ac7-10c3-4f52-8f6a-6e4216af89ed.png)

so i cant access the playerstates pawnprivate var which works on versions like 10.40 and older without any issue, probably some issue with pawn shit as writing to localplayerpawn->currentweapon->customtimedilation (localplayerpawn = static_cast<afortpawn>(localplayer->playercontroller->acknowledgedpawn) also crashes the game (works on other builds as well)

**Comment by Encryqed** [comment]
thanks for telling me. i'll look into it as soon as possible. 👍

**Comment by 0ez** [comment]
np

**Comment by mlodyskiny** [comment]
is the issue actually fixed or did you just close it?

**Comment by Fischsalat** [comment]
close

**Comment by TimmieDevelops** [comment]
rip
