### ISSUE TITLE
TEKKEN 8 Build errors

### ISSUE THREAD

**Issue by riesha** [Encryqed/Dumper-7#100]
you get the idea... 
![image](https://github.com/Encryqed/Dumper-7/assets/58556779/00f1a81f-64bb-441f-a923-1ee67a49a3d8)

![image](https://github.com/Encryqed/Dumper-7/assets/58556779/d4a92b8b-84a1-4c89-898c-65a143e564d6)

[5.2.1-0+UE5-Polaris.zip](https://github.com/Encryqed/Dumper-7/files/14695417/5.2.1-0%2BUE5-Polaris.zip)

**Comment by riesha** [comment]
0_o maybe this is a vscode problem then?
![image](https://github.com/Encryqed/Dumper-7/assets/58556779/a6c14997-e36a-40c7-9613-13e7b270e1d5)

**Comment by riesha** [comment]
CLOSED nevermind im a moron lol i forgot the dev command prompt thing is x32 by default its all good

**Comment by Fischsalat** [comment]
Well, happens.
