### ISSUE TITLE
Access violation for Back4Blood

### ISSUE THREAD

**Issue by Hex0ffset** [Encryqed/Dumper-7#101]
When attempting to generate for Back4Blood with the following change, then an access violation is thrown inside `ObjectArray::InitializeChunkSize` on line 151 (`if (*reinterpret_cast<int32*>(ObjAtIdx374 + i) == 0x374 && *reinterpret_cast<int32*>(ObjAtIdx106 + i) == 0x106)`). This causes it to crash out.

```
diff --git a/Dumper/Generator.cpp b/Dumper/Generator.cpp
index 892610d..cb9e45b 100644
--- a/Dumper/Generator.cpp
+++ b/Dumper/Generator.cpp
@@ -43,7 +43,8 @@ void Generator::InitEngineCore()
        //Off::InSDK::ProcessEvent::InitPE(/*PEIndex*/);

        /* Back4Blood*/
-       //InitObjectArrayDecryption([](void* ObjPtr) -> uint8* { return reinterpret_cast<uint8*>(uint64(ObjPtr) ^ 0x8375); });
+       InitObjectArrayDecryption([](void* ObjPtr) -> uint8* { return reinterpret_cast<uint8*>(uint64(ObjPtr) ^ 0x8375); });
+

        /* Multiversus [Unsupported, weird GObjects-struct]*/
        //InitObjectArrayDecryption([](void* ObjPtr) -> uint8* { return reinterpret_cast<uint8*>(uint64(ObjPtr) ^ 0x1B5DEAFD6B4068C); });
```

However, on a couple of occasions it's managed to not crash out, and continued, but then it just spews out `Could not find GNames!` and gets stuck a little later without generating any files.

Am I missing something to get this working, or is it a legit bug?

**Comment by Fischsalat** [comment]
Back4Blood has GObject encryption, you need to add a lambda for encryption, as shown in the readme.

**Comment by Hex0ffset** [comment]
I'm probably being dumb, bit isn't that what uncommenting InitObjectArrayDecryption under the B4B comment is for?

**Comment by Fischsalat** [comment]
Well, yes, but I'm sure they updated their game in the past 8 months.

**Comment by Hex0ffset** [comment]
OK, thanks! I'll do some more digging.

**Comment by Hex0ffset** [comment]
So reporting back - I'm 99% certain the XOR key is the same still. The game also hasn't been updated since Dec 2022. However I keep hitting the access violation issue, despite fumbling around the code trying to fix it.

**Comment by Fischsalat** [comment]
Ok, I'll take a look at it then.

**Comment by Fischsalat** [comment]
Ok, I finally came around to fixing this. The fixed version is on the [Untested](https://github.com/Encryqed/Dumper-7/tree/Untested) branch, as I haven't had time to test all of the changes for compatibility with other games yet. Remember to uncomment the GObjects decryption!
