### ISSUE TITLE
Enums are wrong for Ready or Not.

### ISSUE THREAD

**Issue by gir489returns** [Encryqed/Dumper-7#103]
When dumping the enumators for Ready or Not (Unreal Engine 4.27) some enumerators the game uses are already UINT8_MAX. This causers the _MAX enumator to then overflow into 256 causing a compiler error.

For example:

```
enum class EGameVersionRestriction : uint8
{
	GVR_NoRestriction              = 0,
	GVR_Base                       = 1,
	GVR_Supporter                  = 2,
	GVR_PreorderBonus              = 3,
	GVR_Demo                       = 255,
	GVR_MAX                        = 256,
};
```

**Comment by Fischsalat** [comment]
This only causes a warning on msvc. Maybe compile with a certain flag, in order for it to work.

**Comment by gir489returns** [comment]
> This only causes a warning on msvc. Maybe compile with a certain flag, in order for it to work.

I am using clang, does the project only support MSVC?

**Comment by Fischsalat** [comment]
MSVC is the only officially supported compiler, yes. I just didn't test any other compilers
