### ISSUE TITLE
Static insert failed with "Wrong size on [..] "

### ISSUE THREAD

**Issue by 0x6c6f63616c** [Encryqed/Dumper-7#104]
Game : Nyan Heroes
Version : UE 5.3

![image](https://github.com/Encryqed/Dumper-7/assets/112541566/4e4d1e77-8fa5-42f4-a57d-63ed6c63f84f)

**Comment by Fischsalat** [comment]
Does anybody even read [Issues](https://github.com/Encryqed/Dumper-7/blob/main/README.md#Issues) or [UsingTheSDK](https://github.com/Encryqed/Dumper-7/blob/main/UsingTheSDK.md#including-the-sdk-into-the-project)?

**Comment by Fischsalat** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/b484f284-dd81-4a58-b4ee-e93b76f09419)
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/39d3768e-69a6-426d-ac00-633cf371cbe7)
