### ISSUE TITLE
Failing to call a function

### ISSUE THREAD

**Issue by imgemmy** [Encryqed/Dumper-7#106]
Sorry first off, I might be completely using the whole SDK wrong. This is my first time messing around in UE.

I am completely failing trying to call a function provided by the SDK.

I start by getting 'BackEndManagerStateAuthenticate'
`SDK::UObject* state = SDK::UObject::FindObjectFast("BackEndManagerStateAuthenticate");`

Then I cast it to its respective class as so;
`SDK::UBackEndManagerStateAuthenticate* state2 = reinterpret_cast<SDK::UBackEndManagerStateAuthenticate*>(state);`

I then want to call `OnAuthenticationReponse()` which is a member of `UBackEndManagerStateAuthenticate`
by doing `state2->OnAuthenticationReponse(&e, 0);`

However it just crashes, by stepping through it I noticed;
`if (Func == nullptr)
	Func = Class->GetFunction("BackEndManagerStateAuthenticate", "OnAuthenticationReponse");`
But even after running `Class->GetFunction()` it still remains a nullptr so when `auto Flgs = Func->FunctionFlags;` runs its just crashes.

**Comment by imgemmy** [comment]
It looks like it's finding it
`000001B87BB94E80 BackEndManagerStateAuthenticate Address |
Class CoreUObject.Class`
Which is outputted from


    SDK::UObject* state = SDK::UObject::FindObjectFast("BackEndManagerStateAuthenticate");
    std::cout << state << " BackEndManagerStateAuthenticate Address | ";  
    std::cout << state->Class->GetFullName() << "\n";

When you say that FindObject returns a UClass describing `BackEndManagerStateAuthenticate`, how would I find the instance of it to call the function? Maybe I'm too naive about how the engine works at this point to see what I'm doing wrong.

Is there a Discord for this repo where I could read & learn more?

**Comment by Fischsalat** [comment]
There is no repository for this dumper, but there is one for UEDumper [here](https://discord.gg/SAYfphkjv7). 

The object called `BackEndManagerStateAuthenticate` is the UClass describing the layout (members, functions) of `UBackEndManagerStateAuthenticate`. The fullname of your object would be something like `Class Something.BackEndManagerStateAuthenticate`. You need to find an object for which the name on the left is not "Class", but "BackEndManagerStateAuthenticate".

**Comment by imgemmy** [comment]
Awesome, thanks for the help! :)
