### ISSUE TITLE
Game Fatal Error Lies of P

### ISSUE THREAD

**Issue by brunob2** [Encryqed/Dumper-7#109]
https://prnt.sc/pmIBz2R2tQCi

https://prnt.sc/U1IywVV1w360

**Comment by Fischsalat** [comment]
????????????????

**Comment by Fischsalat** [comment]
all you did was saying "this game crashes" and sending two links that didn't work. Try harder!

**Comment by brunob2** [comment]
the links work but git had problems with them. copy and paste into browser

**Comment by Fischsalat** [comment]
What's the console output?

**Comment by brunob2** [comment]
lies of p 
https://prnt.sc/yr-5fh1sQybX
This one causes a fatal error in the game
state of decay 2
https://prnt.sc/5NNgEYWaUnM5
this one the game simply closes without any apparent error in the game

**Comment by Fischsalat** [comment]
show the entire output, as text, not 4 screenshots

**Comment by brunob2** [comment]
`Started Generation [Dumper-7]!

Dumper-7 by me, you & him


Searching for GObjects...

Found FChunkedFixedUObjectArray GObjects at offset 0x6f2c1f0

Found 'FNamePool GNames' at offset 0x71CEF40


NameArray::FNameBlockOffsetBits: 0x10

Off::UStruct::Children: 0x48
Off::Field::Next: 0x28
Off::UStruct::SuperStruct: 0x40
Off::UStruct::Size: 0x58
Off::UStruct::MinAlignemnts: 0x5C
Off::UClass::CastFlags: 0xD0
Game uses FProperty system

Off::UStruct::ChildProperties: 0x50
Off::FField::Next: 0x20
Off::FField::Name: 0x28
Off::FField::Flags: 0x30
Off::UClass::ClassDefaultObject: 0x118
Off::UEnum::Names: 0x40
Off::UFunction::FunctionFlags: 0xB0

Off::UFunction::ExecFunction: 0xD8

Off::Property::ElementSize: 0x3C
Off::Property::ArrayDim: 0x38
Off::Property::Offset_Internal: 0x4C
Off::Property::PropertyFlags: 0x40
UPropertySize: 0x78

Off::ArrayProperty::Inner: 0x78
Off::SetProperty::ElementProp: 0x78
Off::MapProperty::Base: 0x78

Off::ULevel::Actors: 0x98

PE-Offset: 0x22C9A90
PE-Index: 0x44

GWorld-Offset: 0x71CAF30

Off::InSDK::Text::TextSize: 0x18
Off::InSDK::Text::TextDatOffset: 0x0
Off::InSDK::Text::InTextDataStringOffset: 0x28

Dumper-7: bIsWeakObjectPtrWithoutTag = false

`
lie of p

**Comment by brunob2** [comment]
`Started Generation [Dumper-7]!

Dumper-7 by me, you & him


Searching for GObjects...

Found FFixedUObjectArray GObjects at offset 0x45dcb30



Could not find GNames!


Found FName::AppendString at Offset 0x1104740

Off::UStruct::Children: 0x38
Off::Field::Next: 0x28
Off::UStruct::SuperStruct: 0x30
Off::UStruct::Size: 0x40
Off::UStruct::MinAlignemnts: 0x44
Off::UClass::CastFlags: 0xB8
Off::UClass::ClassDefaultObject: 0x100
Off::UEnum::Names: 0x48
Off::UFunction::FunctionFlags: 0x88

Off::UFunction::ExecFunction: 0xB0

Off::Property::ElementSize: 0x34
Off::Property::ArrayDim: 0x30
Off::Property::Offset_Internal: 0x50
Off::Property::PropertyFlags: 0x38
UPropertySize: 0x78

Off::ArrayProperty::Inner: 0x78
Off::SetProperty::ElementProp: 0x78
Off::MapProperty::Base: 0x78

Off::ULevel::Actors: 0x-1

PE-Offset: 0x11CB180
PE-Index: 0x35

GWorld-Offset: 0x46D0C08

Off::InSDK::Text::TextSize: 0x18
Off::InSDK::Text::TextDatOffset: 0x0
Off::InSDK::Text::InTextDataStringOffset: 0x28

Dumper-7: bIsWeakObjectPtrWithoutTag = false

LogULCrash:Display: Connectivity test took 789ms
`
state of decay

**Comment by Fischsalat** [comment]
The console output seems good, so I'm not sure why it's crashing. I don't have either of those games so I can't debug the crash.

**Comment by brunob2** [comment]
I really wanted their SDK. Can you try to download them online perhaps?

**Comment by Fischsalat** [comment]
I'm not going to download some crack with 10 viruses just to debug this.

**Comment by brunob2** [comment]
OK. thank you very much.

**Comment by GrigLog** [comment]
Why the hell do you close an issue when you did nothing and it is clearly not solved?

**Comment by Fischsalat** [comment]
Because I don't have the game, so there's nothing for me to test. Feel free to buy the game for me, but I won't waste 42€ just to fix the dumper for a game I don't care about.

**Comment by GrigLog** [comment]
I understand why you dont want to fix the problem yourself but it does not justify marking an issue as closed

**Comment by Fischsalat** [comment]
I just see no point in keeping an issue open when there's no workaround or anything else present there.
