### ISSUE TITLE
[Request] Allow user to supply exact address for things like GObjects from runtime.

### ISSUE THREAD

**Issue by gir489returns** [Encryqed/Dumper-7#110]
Currently, the dumper supplies an exact address for things like Offsets::GObjects, which then requires the user to invoke InitGObjects (well good init m8) at runtime to determine the address. This is great for testing, but for deployment, we usually signature those things as hardcoded offsets just make updating annoying.]

While we could just redump the game again each update, that again requires running Dumper-7, reintegrating the new SDK (Which I see there was a major change that broke compatibility with Clang and now I had to port my project to MSVC) this still requires the original programmer to dump, integrate, recompile and ship a new binary.

Sob story over, what do I want?

Expose a function like InitGObjects that either takes a user-suppled PVOID and sets GObjectsAddress, GNames, and ProcessEvent indiividually, or a giant Init() function that takes all of them with optional nullptr parameters that skips them if the user can't supply it. 
 and (maybe?) GWorld as well.

**Comment by Fischsalat** [comment]
SDKs aren't meant to support more than a single version, as any change to a class, done by the devs, will break the class.

So signature scanning is kin of pointless.

**Comment by gir489returns** [comment]
Yes, that's fair, but minor changes (like the one I'm dealing with on Palworld) cause the build to break when they do hotfixes/minor patches, and I have to redump the SDK each time just because they didn't test their binary before pushing to production.

While I agree for major versions this isn't a good solution, and when I hacked PUBG, they purposefully changed the function stack each time, most games don't do this.

**Comment by Fischsalat** [comment]
In that case you can just replace the offsets in the old sdk.

**Comment by gir489returns** [comment]
Which again

>requires the original programmer to dump, integrate, recompile and ship a new binary.

That could be done automatically by signatures.

**Comment by Fischsalat** [comment]
Feel free to make a pull-request to add that. For now this isn't part of my plans.
