### ISSUE TITLE
problem with Static insert

### ISSUE THREAD

**Issue by zawpi** [Encryqed/Dumper-7#112]
I get a lot of errors that prevent me from using the sdk ( I can't build with these errors)
ps : I don't call any functions, just the basic code provided

![image](https://github.com/Encryqed/Dumper-7/assets/155113964/ef016706-4aab-4e5a-ad7f-a672d308287b)

**Comment by Fischsalat** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/fe79891e-d6e3-437b-a1f5-30bc739b1ec5)
This seems to be a bit strange, offset is 0x20, size 0x8 but the next member is supposed to start at 0x24.

Are there more "Wrong offset" errors after members of type FName? If there aren't please send the console output from generation, as well as a screenshot of FName. Thanks!

**Comment by zawpi** [comment]
no, there's no other wrong offset error on an FName type

[cheat.log](https://github.com/Encryqed/Dumper-7/files/14923056/cheat.log)
![image](https://github.com/Encryqed/Dumper-7/assets/155113964/b9d38386-4c0b-47a8-912f-30a52614ae87)

**Comment by Fischsalat** [comment]
Can you send the console-log from SDK generation? It doesn't need to be the one that was used to create exactly that sdk, re-generating is fine.

**Comment by zawpi** [comment]
That ?
[Dumper.log](https://github.com/Encryqed/Dumper-7/files/14923237/Dumper.log)

or that ? : 

[cmd injection dumper.txt](https://github.com/Encryqed/Dumper-7/files/14923276/cmd.injection.dumper.txt)

**Comment by Fischsalat** [comment]
I've pushed a potential fix for this issue. It would be nice if you could test the commit and let me know if it fixed your issue.

**Comment by zawpi** [comment]
I'll try it as soon as I'm home

**Comment by zawpi** [comment]
I don't know what I did wrong
![image](https://github.com/Encryqed/Dumper-7/assets/155113964/7d1be24f-d1e4-44f6-b87a-b763e33f573d)
![image](https://github.com/Encryqed/Dumper-7/assets/155113964/63a06ba7-c4dc-41c8-ab1e-f2a00443d755)

**Comment by Fischsalat** [comment]
You're missing `CoreUObject_functions.cpp` in your vs project.

**Comment by zawpi** [comment]
Thanks, it finally works. I didn't think that the base code called a function and that I shouldn't add another file.
