### ISSUE TITLE
Access violation for ARK 1.0

### ISSUE THREAD

**Issue by zhangheil** [Encryqed/Dumper-7#115]
![QQ图片20240417043536](https://github.com/Encryqed/Dumper-7/assets/28982242/d61d113c-cfd2-4f89-954b-51ff046fce65)

**Comment by zhangheil** [comment]
After manually modifying PropertyFlags=0x38 in the debugger, I guessed the value. The previous error disappeared, but a new error occurred
![Uploading QQ图片20240417043536.png…]()

**Comment by zhangheil** [comment]
After manually modifying PropertyFlags=0x38 in the debugger, I guessed the value. The previous error disappeared, but a new error occurred
![1](https://github.com/Encryqed/Dumper-7/assets/28982242/fba6569f-40a1-429d-b63b-552753a11f40)

**Comment by zhangheil** [comment]
The problem has been resolved, and SDK export will be done after correct repair
![2](https://github.com/Encryqed/Dumper-7/assets/28982242/30f3d73c-1a43-4b8c-ac9f-9288010f000b)

**Comment by prizrak56** [comment]
@zhangheil 
can you tell me what you did to make the error disappear or dump a dump if it’s not difficult
