### ISSUE TITLE
Access violation on Predecessor - works fine in a older version of Dumper-7.

### ISSUE THREAD

**Issue by a1mb0t46** [Encryqed/Dumper-7#118]
Works fine on older versions.

See the screenshot below.

![image](https://github.com/Encryqed/Dumper-7/assets/72723185/6bbf2af4-c26c-4bca-bfbe-b013f5dbf29c)

**Comment by Fischsalat** [comment]
What's the callstack, what are the values of some of the variables before crashing?

**Comment by a1mb0t46** [comment]
Sorry for the late reply.

Seems to be InitAlignmentsAndNames() that crashes it after it loops for a second or third time.

![image](https://github.com/Encryqed/Dumper-7/assets/72723185/567c1dbc-a656-43cb-bf6e-1506c589cea1)

Above is the callstack from VS.

**Comment by a1mb0t46** [comment]
FMulticastInlineDelegateProperty_ is the reason for the crash as far as I can see.

As soon as a class member is FMulticastSparseDelegateProperty_ it crashes. Happened consistently with: UActor, UTypedElementSelectionSet, UActorComponent. Only 3 classes I checked.

**Comment by Fischsalat** [comment]
Try getting some property of type FMulticastInlineDelegateProperty and print the CastFlags of it's class (there's a StringifyCastFlags function for that). You should be able to do this after `InitEngineCore()` has finished and everything is still valid.

I suspect the castflags have been changed and maybe cause some issue with it. Any chance you're on SoT?

**Comment by a1mb0t46** [comment]
> Try getting some property of type FMulticastInlineDelegateProperty and print the CastFlags of it's class (there's a StringifyCastFlags function for that). You should be able to do this after `InitEngineCore()` has finished and everything is still valid.
> 
> I suspect the castflags have been changed and maybe cause some issue with it. Any chance you're on SoT?

I will get back to you later tonight.

I tried it on Predecessor and another game that works with a older version of the dumper.

**Comment by Fischsalat** [comment]
What injection method are you using, loadlibrary or manual map? Cause I just downloaded Predecessorr, started it without anticheat and dumped fine on both debug and release configuration with the latest commit from the main branch.
