### ISSUE TITLE
8.51 dump issues

### ISSUE THREAD

**Issue by nexxnexx** [Encryqed/Dumper-7#12]
LoginId:c29ae7924c473cd763a05e970ce8e17e
EpicAccountId:f8c93c8174944b7088aab0920a8ab9fa

Unhandled exception

Dumper_7!UEObject::GetIndex() [E:\Dumper-7-main\Dumper\UnrealObjects.cpp:25]
Dumper_7!ObjectArray::Init() [E:\Dumper-7-main\Dumper\ObjectArray.cpp:176]
Dumper_7!Generator::Init() [E:\Dumper-7-main\Dumper\Generator.cpp:11]
Dumper_7!MainThread() [E:\Dumper-7-main\Dumper\Main.cpp:35]
kernel32
ntdll

**Comment by nexxnexx** [comment]
![Capture](https://user-images.githubusercontent.com/95999940/229836149-7e6cb4de-5b5a-452e-a5f0-57990c44a1de.PNG)

**Comment by Fischsalat** [comment]
at what time do you inject the dll? Have you tried several times?

**Comment by nexxnexx** [comment]
yeah, i inject it in lobby
