### ISSUE TITLE
Access Violation unity 5.21

### ISSUE THREAD

**Issue by ossmannnn** [Encryqed/Dumper-7#120]
Game: Dead by Daylight steam (they recently updated)
Unity version: 5.21

The tool worked great on the previous version of the game (they were using ue4).
Now there's an access violation upon injecting. I linked a screenshot with all the details

![Screenshot](https://github.com/Encryqed/Dumper-7/assets/167902531/bc91d22c-85d4-4bdb-8111-69100147eeb0)

**Comment by Fischsalat** [comment]
I'm aware of this crash, I'm currently investigating why FName::AppendString isn't found.

**Comment by Fischsalat** [comment]
Try the [Untested](https://github.com/Encryqed/Dumper-7/tree/Untested) branch please. Let me know if it works.

**Comment by Fischsalat** [comment]
perfect, does the SDK work too?

**Comment by August2211** [comment]
> perfect, does the SDK work too?

Seems like it, it compiles fine and I was able to loop objects
Anything specific I should test?

**Comment by Fischsalat** [comment]
Are you using AppendString or GNames, cause someone else complained that AppendString was crashing on dbd. And GNames too apparently (in the SDK).

**Comment by August2211** [comment]
> Are you using AppendString or GNames, cause someone else complained that AppendString was crashing on dbd. And GNames too apparently (in the SDK).

Yes
In my object loop I printed Object->GetFullName()

**Comment by Fischsalat** [comment]
Hm, guess it's his dll setup that causes AppendString to crash. Could you maybe try forcing the dumper to use GNames (`FName::Init(true)`) and test if GetFullName() works in the SDK? Thanks!

**Comment by August2211** [comment]
Might be a skill issue but console output is fucked after using FName::Init(true) and doing std::cout << Object->GetFullName() << std::endl;

![image](https://github.com/Encryqed/Dumper-7/assets/53059031/c70f1976-01d9-47ae-8571-57325631e19f)

**Comment by Fischsalat** [comment]
Hm, I guess I still need to fix that issue then.

**Comment by Fischsalat** [comment]
not as of now. I don't have dbd so it's kinda hard to debug. I'll have to find someone that has the game and is willing to test some stuff.

**Comment by IDKTHISSS** [comment]
I can give you dbd account in EpicGames if you need.

> not as of now. I don't have dbd so it's kinda hard to debug. I'll have to find someone that has the game and is willing to test some stuff.

**Comment by Fischsalat** [comment]
Would be nice, send me a DM on discord: `fischsalat`

**Comment by Fischsalat** [comment]
Fixed.
