### ISSUE TITLE
static_assert failed: wrong offset/wrong size

### ISSUE THREAD

**Issue by ApeArmy** [Encryqed/Dumper-7#121]
UE5 Game Version: 5.3.2
Followed everything step by step from the UsingTheSDK, using the basic example of DllMain and MainThread for main.cpp (using #include "SDK.hpp")
I dumped while in the game (not menu) incase that is relevant.
Sorry if this is due to a user error, I used all the available documentation to the best of my ability.

This video shows all the build only errors present. (Assuming the box shown in the error list is all you have to change to set it to show only build errors, sorry if I'm wrong)
https://github.com/Encryqed/Dumper-7/assets/69106259/227cefe0-2217-4839-9d23-64400b818494

These 2 pictures, one may be the top error you're looking for. (one is shown on the top of the error list with no sorting applied, the other is from the "error count exceeds" error)
![devenv_CdUgAYrnCl](https://github.com/Encryqed/Dumper-7/assets/69106259/023fea68-8729-4c2e-8dc2-a9b38824d483)
![devenv_a2Hh4DkFfg](https://github.com/Encryqed/Dumper-7/assets/69106259/686d60b4-5078-4175-8416-752ca6c7659b)

Thank you for your time, and please let me know if I missed any vital information.

**Comment by Fischsalat** [comment]
Damn, it was one of the best issues I've read on this github repository (lots of good info and well written), I was actually looking forward to handling it once I'd be on my PC.

**Comment by ApeArmy** [comment]
> Damn, it was one of the best issues I've read on this github repository (lots of good info and well written), I was actually looking forward to handling it once I'd be on my PC.

I figured it could of been due to me using a more debugged version of the game, didn't want to waste anybody's time, a earlier version of 5.3.1 worked without issues, so I suppose it could be a 5.3.2 issue.

If your able to fix it off of what I shown, then that's great, if you need additional info I would prefer to message you directly about it if possible.

**Comment by Fischsalat** [comment]
Well, I'm not able to fix anything off of the information you provided, as you deleted it. If you want to message me, send me a friendrequest on discord `fischsalat`.
