### ISSUE TITLE
Add FMemory functions.

### ISSUE THREAD

**Issue by raax7** [Encryqed/Dumper-7#122]
Hey, this isn't really an issue but more of a feature request.

I think you should add some basic FMemory functions like FMemory::Malloc, FMemory::Realloc and FMemory::Free. This is very useful because you can then add proper destructors to FStrings, TArrays, etc. I believe, if the memory was allocated by the engine (i.e. the temp FString that is passed into AppendString) you are unable to free it normally, and have to use UE's memory management functions.

It shouldn't be too hard to add these, since the code stays pretty much identical across many, many versions of UE. Hence, so do the signatures.

If you think this would be a good addition, then I could make a pull request and try to add it myself. Although, I do think it would be better if you were to add it since, the code would most likely fit in better with the overall project design.

**Comment by Fischsalat** [comment]
I actually tried that. Twice. Both attempts have failed because FMemory functions crash when freeing a lot of memory in a short time. I couldn't track down the cause of the problem so I have given up on both attempts. 

I removed all of the Array/Set/Map related code and tried just allocating and freeing memory blocks quickly, and it also caused a crash.

The implementations I used are available in my [UnrealContainers](https://github.com/Fischsalat/UnrealContainers) repository. The current set of containers in the SDK is UnrealContainersNoAlloc.h.

**Comment by raax7** [comment]
Hey, thank you for such a quick response.

I just went and tested this for myself, and I'm not having any crashes on my UE4.22 game using FMemory::Malloc, FMemory::Realloc and FMemory::Free.

I ran 2 tests, one allocating lots of memory, reallocating it and then immediately freeing it. The second letting the memory stay allocated, and then freeing all allocated memory at once after. Neither of these resulted in crashes.

This first image is while the test was running. You can see on the left performance monitor showing that the memory is actually being allocated. (performance monitor is displaying the Private Bytes count of the process)
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/d114eae1-341d-49a2-8d16-125f0c1834b3)

This second image is without doing all the allocation and freeing, just to prove that it was my memory allocation causing the spikes.
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/b64caf92-66d0-46a7-befd-51c0fc3f85ae)

This third image is the code I ran for these tests.
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/2f99d539-2364-4410-8c74-839d91e6457f)

I can't think of any reason these tests wouldn't show the same issue you had, so any insight would be great!

**Comment by Fischsalat** [comment]
Ok, there's two more things you could test:
1. Try allocating blocks of a random size (in a range of cause) and freeing them
2. Try using only FMemory::Realloc, but use it as Malloc and Free to by passing the right params 
 - `Realloc(nullptr, 0x10)` is `Malloc(0x10)`
 - `Realloc(Ptr, 0x0)` is `Free(Ptr)`

**Comment by raax7** [comment]
Just tested this, and I'm not getting any crashes either. I also tested it on a bunch of different engine versions.

UE4.24
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/ea808c16-f021-45f7-9274-3da29adf3dc1)

UE4.25
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/643ec200-2b63-4f26-86f3-f5b4aa4831a1)

UE5.0.1
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/8eb38db3-5f28-4ff7-bc09-386e3d71883c)

I also tested on UE4.20 but my FMemory::Free sig was incorrect, and I couldn't be bothered to update it yet. If you just ignore the freeing part of the first test, it still wasn't crashing.

Here's the code I used, if it wasn't what you wanted please let me know.
![image](https://github.com/Encryqed/Dumper-7/assets/142668843/0f433f02-f0d5-4986-9d03-7ac44fc5fb00)

**Comment by Fischsalat** [comment]
Did you try the 2nd option too, using Realloc for everything? Also maybe increase the number of allocations to around 0x40000 on the test where you alloc and then free instantly.

**Comment by Fischsalat** [comment]
.

**Comment by raax7** [comment]
Hi, yes sorry I forgot about this. I will check this again when I'm free today.
