### ISSUE TITLE
GetSize error

### ISSUE THREAD

**Issue by yuvalperez** [Encryqed/Dumper-7#127]
![image](https://github.com/Encryqed/Dumper-7/assets/126117117/a4b64b48-f0b3-411c-a4e8-239d77a6f832)
![image](https://github.com/Encryqed/Dumper-7/assets/126117117/2d0593b3-4b4e-461c-86c5-55df1fa83c3e)
hi can u help me i got this error

**Comment by Fischsalat** [comment]
ARK is not supported, you should use another generator (like CheatGear) for that.
