### ISSUE TITLE
Build Error: 'FunctionIndex': undeclared identifier in Utils.h

### ISSUE THREAD

**Issue by ikonikisop** [Encryqed/Dumper-7#129]
Hello, i tried compiling it and this error popped up? I never had it before and yesterday before your recent commit it complied completely fine. Not sure if i did something wrong. I cloned a fresh version and this error still popped up when building.

![image](https://github.com/Encryqed/Dumper-7/assets/129855365/191902c0-0dd5-4105-a56e-d1322f5d89e2)

**Comment by Fischsalat** [comment]
Bruh, GitHubs merge functions suck. I'll fix it later

**Comment by ikonikisop** [comment]
> Bruh, GitHubs merge functions suck. I'll fix it later

Awesome, thank you.

**Comment by Fischsalat** [comment]
fixed it
