### ISSUE TITLE
9.00 crashes when using sdk

### ISSUE THREAD

**Issue by ILoveTacosFromJITB** [Encryqed/Dumper-7#13]
When I try to print the address of any object I get 0000000, and if i use GetFullName or GetName the function crashes

Here is the code and the place it crashes at is when i print with getfullname in dllmain.cpp
![image](https://user-images.githubusercontent.com/89064551/233458075-c260f735-ece9-4053-8382-93d04223e835.png)

here is where GetFullName() is
![image](https://user-images.githubusercontent.com/89064551/233457563-b6cc9b6c-8c5b-457b-808b-3ff78d72480a.png)

and the crash log reads:

LoginId:ced81d57431a50cab505e3a8f66ab5e9
EpicAccountId:

Unhandled exception

FortniteSDK!SDK::UObject::GetFullName() [pathtoproject\SDK\CoreUObject_functions.cpp:28]
FortniteSDK!DLLMain() [pathtoproject\dllmain.cpp:23]
kernel32
ntdll

**Comment by ILoveTacosFromJITB** [comment]
left out the line numbers in the screenshot on accident

in CoreUObject_functions.cpp line 28 it crashes at: if (Class)

**Comment by Fischsalat** [comment]
Look at the object dump, on s9 the UFortEngine instance isn't called "FortEngine_0", but "FortEngine_2102482". (Number isn't correct, look at your objects dumpf for reference.

If you don't have an object dump you can generate one by putting a call to ObjectArray::DumpObjects() before Generatro::GenerateSDK() in Dumper-7.

**Comment by ILoveTacosFromJITB** [comment]
That fixed the problem, Thank you so much!
