### ISSUE TITLE
static_assert ERROR 

### ISSUE THREAD

**Issue by scx1125** [Encryqed/Dumper-7#132]
![image](https://github.com/Encryqed/Dumper-7/assets/34766580/7a38f60f-7bef-41ab-b159-5832cf4d0422)
```c++
// ScriptStruct JsEnv.PropertyMetaRoot
// 0x0008 (0x0008 - 0x0000)
struct FPropertyMetaRoot final
{
public:
	class UItemMaterialControllerActorData_C*     None;                                              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         None_0;                                            // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         None_1;                                            // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FWorldPartitionStreamingQuerySource    None_2;                                            // 0x0000(0x0030)(HasGetValueTypeHash)
	struct FVector                                None_3;                                            // 0x0000(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSCameraConfig                         None_4;                                            // 0x0000(0x0738)(HasGetValueTypeHash)
	class AActor*                                 None_5;                                            // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FIntPoint                              None_6;                                            // 0x0000(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         None_7;                                            // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimationAsset*                        None_8;                                            // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNotifyEvent                       None_9;                                            // 0x0000(0x00C8)(HasGetValueTypeHash)
	class UAnimSequenceBase*                      None_10;                                           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  None_11;                                           // 0x0000(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   None_12;                                           // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 None_13;                                           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 None_14;                                           // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FPropertyMetaRoot) == 0x000008, "Wrong alignment on FPropertyMetaRoot");
static_assert(sizeof(FPropertyMetaRoot) == 0x000008, "Wrong size on FPropertyMetaRoot");
static_assert(offsetof(FPropertyMetaRoot, None) == 0x000000, "Member 'FPropertyMetaRoot::None' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_0) == 0x000000, "Member 'FPropertyMetaRoot::None_0' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_1) == 0x000000, "Member 'FPropertyMetaRoot::None_1' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_2) == 0x000000, "Member 'FPropertyMetaRoot::None_2' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_3) == 0x000000, "Member 'FPropertyMetaRoot::None_3' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_4) == 0x000000, "Member 'FPropertyMetaRoot::None_4' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_5) == 0x000000, "Member 'FPropertyMetaRoot::None_5' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_6) == 0x000000, "Member 'FPropertyMetaRoot::None_6' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_7) == 0x000000, "Member 'FPropertyMetaRoot::None_7' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_8) == 0x000000, "Member 'FPropertyMetaRoot::None_8' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_9) == 0x000000, "Member 'FPropertyMetaRoot::None_9' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_10) == 0x000000, "Member 'FPropertyMetaRoot::None_10' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_11) == 0x000000, "Member 'FPropertyMetaRoot::None_11' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_12) == 0x000000, "Member 'FPropertyMetaRoot::None_12' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_13) == 0x000000, "Member 'FPropertyMetaRoot::None_13' has a wrong offset!");
static_assert(offsetof(FPropertyMetaRoot, None_14) == 0x000000, "Member 'FPropertyMetaRoot::None_14' has a wrong offset!");
```

**Comment by StoNeD510** [comment]
Same issue just trying to follow the steps and compile the example.

**Comment by Fischsalat** [comment]
Are other class members name? Because that class looks like the engine just unloaded all properties in `FPropertyMetaRoot`.
The offsets are wrong too. 

Also on a sidenote, github allows for code formatting, use it!

**Comment by Lok3rn3t** [comment]
![1SS](https://github.com/Encryqed/Dumper-7/assets/71749209/c5ea46d8-0f63-4d6b-9bdd-af561f609891)
Such an error

**Comment by Fischsalat** [comment]
just send the sdk, else we're getting nowhere

**Comment by Lok3rn3t** [comment]
[Dumper-7.zip](https://github.com/Encryqed/Dumper-7/files/15446768/Dumper-7.zip)

**Comment by Fischsalat** [comment]
Interesting. Maybe read through UsintTheSDK.md again.
\
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/5fe114ff-960d-4cb0-ac14-a2a4afc9cd25)
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/b9e66de3-6df9-495e-81b6-cba3383a8444)

**Comment by Lok3rn3t** [comment]
> Interesting. Maybe read through UsintTheSDK.md again. ![image](https://private-user-images.githubusercontent.com/64608145/333908218-5fe114ff-960d-4cb0-ac14-a2a4afc9cd25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NjExNTksIm5iZiI6MTcxNjc2MDg1OSwicGF0aCI6Ii82NDYwODE0NS8zMzM5MDgyMTgtNWZlMTE0ZmYtOTYwZC00Y2IwLWFjMTQtYTJhNGFmYzljZDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDIyMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDIxMzM1ZTVjZjI4ZjYwMTE0YTg2MjFmY2Q1ZWFiMThlNGJjYjNjMWQ5YjAyNGM5NDM1M2M4OGVlN2VhZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BZ3l6uJrjlJpDz2nGLW66TQwtTvgItV7FL2Z4rDogO0) ![image](https://private-user-images.githubusercontent.com/64608145/333908275-b9e66de3-6df9-495e-81b6-cba3383a8444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NjExNTksIm5iZiI6MTcxNjc2MDg1OSwicGF0aCI6Ii82NDYwODE0NS8zMzM5MDgyNzUtYjllNjZkZTMtNmRmOS00OTVlLTgxYjYtY2JhMzM4M2E4NDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDIyMDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDU1YzVjZGIzYWU1YTA0NmM0YTM1MGU0OGVkYTliYzJjNTQ4MDQ2ZjNlZDgxNzlhZjdmYWNmYTVmODQyMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oPNjaVvDm52hPouU38Sba3Xc4UT6n5DpynCY_Ip3ZkQ)

The problem disappears if you use the sdk that you generated in the game menu, if you generated while you went to the world itself, then similar errors appear, did you use my sdk?

**Comment by Fischsalat** [comment]
I used the one you sent me.

**Comment by Lok3rn3t** [comment]
I just itegrated a full sdk.

**Comment by Fischsalat** [comment]
so everything works now?

**Comment by Lok3rn3t** [comment]
I import the full sdk, that is include “SDK.hpp”, if you generate in the main menu of the game, everything is ok, if in the world, the sdk generator generates another +500 files, and a similar error occurs, I sent you the sdk with which I had a problem, if you do not follow your example and connect the full sdk with your same example occurs a similar error

**Comment by Fischsalat** [comment]
I used the sdk you sent me and threw it into my test project with all of the same setup as UsingTheSDK.md. I didn't get a single compiler error and the dll built fine.

**Comment by Lok3rn3t** [comment]
I don't know if it's just me, I don't use 
```cpp 
#include “SDK/Engine_classes.hpp”
``` 
as in your example, but 
```cpp
#include “SDK.hpp”
```

**Comment by Fischsalat** [comment]
I also included the whole SDK. So yea, make sure you set it up correctly. Choose latest c++ version too.
