### ISSUE TITLE
Access violation for ARK 1.0 (Survival Evolved)

### ISSUE THREAD

**Issue by prizrak56** [Encryqed/Dumper-7#133]
I saw a guy had the same problem, I added the same thing as he did but it didn’t help me
https://github.com/Encryqed/Dumper-7/issues/115
![image](https://github.com/Encryqed/Dumper-7/assets/76444878/5338aad9-4077-4fd9-8e74-dd22b3edcdb3)
![image](https://github.com/Encryqed/Dumper-7/assets/76444878/e7459957-ae54-4759-833d-acf6e144e526)
![image](https://github.com/Encryqed/Dumper-7/assets/76444878/13ee0354-47ab-4279-857d-a617686d5b87)

**Comment by Fischsalat** [comment]
are you sure you did it right, cause on the screenshots it's still -1

**Comment by prizrak56** [comment]
> are you sure you did it right, cause on the screenshots it's still -1

Well, it seems like he only added 1 line

**Comment by Fischsalat** [comment]
Ok well, explain how it's supposed to be working if the offset printed for Off::Property::PropertyFlags is still -1 even after you set it ot 0x38 a line above. Did you just forget to recompile?
