### ISSUE TITLE
Not a working example for the Bronzebeards Tavern game

### ISSUE THREAD

**Issue by Lok3rn3t** [Encryqed/Dumper-7#134]
```cpp   
    ULevel* Level = World->PersistentLevel;
    TArray<AActor*>& volatile Actors = Level->Actors;

    for (AActor* Actor : Actors)
    {
        /* The 2nd and 3rd checks are equal, prefer using EClassCastFlags if available for your class. */
        if (!Actor || !Actor->IsA(EClassCastFlags::Pawn) || !Actor->IsA(APawn::StaticClass()))
            continue;

        APawn* Pawn = static_cast<APawn*>(Actor);
        // Use Pawn here
    }
```
For some reason this piece of code stopped working in the new version of the dumper

**Comment by Fischsalat** [comment]
What is that supposed to mean? "stopped working in the new version of the dumper"?

Is it crashing, is it not compiling, is there any other issue? Are you replacing any of the types?


For real, what the fuck am I supposed to do now? I have by far not enough information to do anything. Why would you open an issue like that? Do you think I'm magic?

I'm sorry to disappoint you, but I'm not a fucking wizard. So if you want me to fix anything, give me sufficient information!

**Comment by Lok3rn3t** [comment]
Sorry man 😂, didn't think to post about the problem itself.
I tried to compile it now and it compiled 😅, really sorry.
Thank you for the wonderful dumper. <3

**Comment by Lok3rn3t** [comment]
No offense
