### ISSUE TITLE
[ ERROR LNK2001 ] Unresolved External Symbol

### ISSUE THREAD

**Issue by funaydmc** [Encryqed/Dumper-7#135]
This error always appears whenever I try to import any UnrealEngine class or function from the SDK.
I double-checked several times to make sure I followed the steps described in the "UsingTheSDK" correctly.
I am a newbie, if there are any fundamental mistakes, please let me know if you suspect that I am making them.

`error LNK2001: unresolved external symbol "public: static class SDK::UWorld * __cdecl SDK::UWorld::GetWorld(void)" (?GetWorld@UWorld@SDK@@SAPEAV12@XZ)`

If the information I provide is insufficient, I am happy to respond to any requests for information.

**Comment by Fischsalat** [comment]
Linker errors occur when the linker can't find the implementation of a function.

The implementation is (most of the times) in .cpp files, so you need to add those to your project (if that .cpp file contains the implementation of a function you're calling).

Don't add all . cpp files. See the setup part of UsingTheSDK.
