### ISSUE TITLE
Access Violation SDK::UObject::IsA() - Unreal 5.1.1.0

### ISSUE THREAD

**Issue by penzer86** [Encryqed/Dumper-7#136]
Today the game is updated, then I use Dumper-7 to dump and update SDK but my program is doesn't work like normal

![sdk_error_1](https://github.com/Encryqed/Dumper-7/assets/122106482/7aab09d6-f8d0-465c-a766-c914d7f3e68b)
![sdk_error_2](https://github.com/Encryqed/Dumper-7/assets/122106482/500b56ad-68b6-4989-ad7a-8c008449f62b)

**Comment by Fischsalat** [comment]
does printing the name of the actor work?

**Comment by Fischsalat** [comment]
your actor is invalid then. Try putting volatile in there (like in UsintTheSDK.md)

**Comment by Fischsalat** [comment]
Well, that kinda sucks. Did you try changing it to a normal for loop (with volatile for the array).
I'd like to see if that works, might be an issue in the UnrealContainers implementation if it works.

**Comment by n0bodysec** [comment]
Afaik marking a ref variable as volatile is non sense.

Try something like this

```
SDK::TArray<SDK::ULevel*>& levels = GWorld->Levels;
for (int j = 0; j < levels.Num(); j++)
{
	if (!levels.IsValidIndex(j)) continue;

	SDK::ULevel* currentLevel = levels[j];
	if (!currentLevel) continue;

	for (int32_t i = 0; i < currentLevel->Actors.Num(); i++)
	{
		SDK::AActor* curActor = currentLevel->Actors[i];
		if (!curActor) continue;

		// do something
	}
}
```

**Comment by Fischsalat** [comment]
For the love of god please stop doing this. You're guaranteed to be within a valid index-range when you start at 0 and you're incrementing until Num() is reached.

You only need to check IsValidIndex when getting the index from elsewhere, or when changing your `i` to something less than 0;
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/a80fc17a-c5eb-4c9d-b4e2-4c836c5e5642)

**Comment by Fischsalat** [comment]
Ok, I guess for it to be checked 100% you could use a `const volatile TArray<AActor*>&`, but in that case the `Num()` function (and others) would need to be marked `volatile`. Hmmm. 

See comparison:
Non-Volatile (Reading NumElements once): https://godbolt.org/z/rE6vbTeEa
Volatile (Re-reading NumElements each iteration): https://godbolt.org/z/c5W8esE9z

**Comment by n0bodysec** [comment]
> You only need to check IsValidIndex when getting the index from elsewhere, or when changing your `i` to something less than 0;

I know lol, I was just making it extra safe for him cuz his crash has no sense.

**Comment by n0bodysec** [comment]
@penzer86 would you mind to share in which game are you working on? I would like to test it.

**Comment by Fischsalat** [comment]
.

**Comment by n0bodysec** [comment]
I don't think he's coming back

**Comment by Fischsalat** [comment]
Me neither, I guess he doesn't need this issue anymore.
