### ISSUE TITLE
E1542 | some enumerator constants cannot be represented by "int"

### ISSUE THREAD

**Issue by Nikitashev1327** [Encryqed/Dumper-7#137]
Hello,
I apologize for maybe a silly question, but I keep getting this error in Basic.hpp file whenever I try to use the generated SDK.
Error is in EClassFlags, screenshot below
SDK generates with no errors, game Palia
Most likely mistake on my side just can't figure out what it is for like 3rd day :(
![image](https://github.com/Encryqed/Dumper-7/assets/34217490/a988e7c4-25ad-4e48-b551-9e01c5317ba4)

Also after this error a number of "static assertion failed", however I assume its cascading because the one enum error?

**Comment by Nikitashev1327** [comment]
Yes, can't build the project with static assert errors :(

**Comment by Fischsalat** [comment]
send the sdk please

**Comment by Fischsalat** [comment]
Seems like the sdk is fine. Make sure you turn the errors to "build only".
\
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/3de1660d-3a7d-4ed8-ac20-e2db87560b29)
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/efdff845-7849-4ea1-856f-c6ed67d1e398)

**Comment by Encryqed** [comment]
Works fine.
