### ISSUE TITLE
Finding specific offsets

### ISSUE THREAD

**Issue by itfoldy** [Encryqed/Dumper-7#138]
So I’m a bit confused with this dumper, it successfully does what it’s supposed to, but how do you actually find specific offsets like PlayerController, PersistentLevel etc, I’m looking in engine_classes.hpp of the SDK dump and unsure how to retrieve the offsets, or where they are, thank you

**Comment by Fischsalat** [comment]
The offets are in the comments on the right hand side next to the class-member-names.

If you're internal (DLL) avoid using offsets directly. If you're external, please make a namespace for offsets, don't hardcode them in code.

**Comment by itfoldy** [comment]
Hi, thank you I have understood that now, wanted to confirm. Is there any way to get this "Engine" address, in UE4 I remember using this tool which had the feature, sorry for the terrible questions :/
![image](https://github.com/Encryqed/Dumper-7/assets/76444336/f27a2535-aa89-437d-b8af-48ef27225753)

**Comment by Fischsalat** [comment]
Use SDK::UEngine::GetEngine() or re-implement its logic.
