### ISSUE TITLE
Capitalization of enum values causes wrong mapping generation

### ISSUE THREAD

**Issue by adainrivers** [Encryqed/Dumper-7#139]
https://github.com/Encryqed/Dumper-7/blob/edbd0bf06bec1163859375ad2d07426913b1ae74/Dumper/UnrealTypes.cpp#L39C7-L42C3

Because of this transformation, the enum names from the mapping sometimes doesn't match the actual values, making it harder to work with typed languages.

**Comment by Fischsalat** [comment]
Ah fuck. Well, I needed to remakethe IsValidName function anyways, to support characters from other languages. I guess this will just be one more thing to consider.

**Comment by Fischsalat** [comment]
Actually try the [Unicode-Names](https://github.com/Encryqed/Dumper-7/tree/Unicode-Names) branch. There's no forced capitalization of names on there at the moment.

Keep the issue open tho.
