### ISSUE TITLE
Plans to dump Mappings as well as SDK?

### ISSUE THREAD

**Issue by GMatrixGames** [Encryqed/Dumper-7#14]
Since this is more actively maintained than UnrealMappingsDumper for the time being, are there plans to add support for dumping mappings as well as the SDK?

**Comment by Fischsalat** [comment]
There certainly are no existing plans on doing that since I'm not even sure what mappings are. But if you need it I might steal half of shades codebase to add support for that.

**Comment by Fischsalat** [comment]
Support added.
