### ISSUE TITLE
LNK Issue

### ISSUE THREAD

**Issue by Vincent1232** [Encryqed/Dumper-7#140]
so I already have the FortniteGame_functions.cpp file in Visual Studio but I keep getting 1 error from building the dll.
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/782e5a00-638d-40f7-903c-b42a304def6b)
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/ec802fdc-04d0-4014-8714-79d1f7b65c7d)
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/c48e2ac2-ca92-45eb-a288-137938eb30d8)
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/491942fb-f5aa-478e-905b-1ea2c35efc06)
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/25266001-6a59-437c-8069-16dbbaf43df0)

**Comment by Fischsalat** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/0d7ffc4f-d78f-489e-995d-a08e4a56b477)
how about the .cpp file for that one?

**Comment by Vincent1232** [comment]
> ![image](https://private-user-images.githubusercontent.com/64608145/335496035-0d7ffc4f-d78f-489e-995d-a08e4a56b477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDM3NTAsIm5iZiI6MTcxNzE0MzQ1MCwicGF0aCI6Ii82NDYwODE0NS8zMzU0OTYwMzUtMGQ3ZmZjNGYtZDc4Zi00ODllLTk5NWQtYTA4ZTRhNTZiNDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA4MTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWU2MjE1ZTE2OTY4MDdjYWVmMTg4OTRhOWQyZjZiYzEzYTBhNDFmYTk0MDZjNzAzOGNmYmQ2NzY2ZTM0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8C_yANZARl8XYED6jdwN9HVbUx9VrIs5eMwaqBMLtqY) how about the .cpp file for that one?

![image](https://github.com/Encryqed/Dumper-7/assets/98626520/3f588db7-5ae2-49f5-8786-39cb08fe3d91)
already had it but still, the same issue I had

**Comment by Vincent1232** [comment]
okay nvm i fixed the issue thanks Fischsalat
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/c8912b5b-fd70-4c3e-bbbb-61abf594b22f)
