### ISSUE TITLE
Error on line (172) : Length <=0

### ISSUE THREAD

**Issue by 860000023** [Encryqed/Dumper-7#142]
hi,I used a free UE4 game from Steam to test the dumper. When I executed the MemberManager::Init(); function, it prompted an error: Error on line (172) : Length <=0. Then I found that the generated Player_BP_ was missing the structs.hpp file, and player_BP_function.cpp could not be opened with Visual Studio. It prompted "unexpected end of file in comment". I opened it with Notepad and found that there were many garbled characters in the comments, and the function names were also garbled. It looked something like this:

```
// Function Player_BP.Player_BP_C.b
@?
// (BlueprintCallable, BlueprintEvent)

void APlayer_BP_C::b___()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_BP_C", "b
@?);

	UObject::ProcessEvent(Func, nullptr);
}
```
Game link: https://store.steampowered.com/app/1727650/Deathly_Stillness/

**Comment by 860000023** [comment]
I suspect this might be caused by the function names being in Chinese.

**Comment by Fischsalat** [comment]
I'm yet to fix chinese (and other non ascii) characters in names. It's on my list of things to do.

**Comment by 860000023** [comment]
Thank you for your response, this is a great open-source project.
