### ISSUE TITLE
MarkArrayDirty

### ISSUE THREAD

**Issue by MrJohnson2-0** [Encryqed/Dumper-7#143]
This isn't really an error but could you add the following functions to the sdk, it would be useful for certain games, MarkArrayDirty, Free, MarkItemDirty, I tried to add them myself but when I did I got 100 errors

**Comment by Fischsalat** [comment]
I wont add the "MarkDirty" functions because they are not really useful to many people. I tried to add Free before, it crashed randomly. So I can't really add that either.

**Comment by Vincent1232** [comment]
> I wont add the "MarkDirty" functions because they are not really useful to many people. I tried to add Free before, it crashed randomly. So I can't really add that either.

Why don't you use bool to make it true to use mark dirty?

**Comment by Fischsalat** [comment]
Because I don't want to spend the time implementing it. 

You can add those functions yourself to your fork of the generator if you want.

**Comment by MrJohnson2-0** [comment]
@Fischsalat see my problem is that when I remotely change one thing in the sdk I get 1000 Errors and the sdk wants to get all upset

**Comment by Vincent1232** [comment]
Yeah because of all those errors in them.

**Comment by MrJohnson2-0** [comment]
no because when I add the function to a different sdk, one that isn't this one, I get no errors and it works fine

**Comment by Fischsalat** [comment]
Well, what are you doing?
