### ISSUE TITLE
Access Violation, UE4.27 | The Texas Chain Saw Massacre

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#149]
![image](https://github.com/Encryqed/Dumper-7/assets/85035681/43c5e344-f871-448d-88d2-751567f85734)

**Comment by Fischsalat** [comment]
Use the latest commit from Main branchand let me know if it still crashes.

**Comment by Fischsalat** [comment]
Call the `ObjectArray::DumpObjects()` function right after `FName::Init()` in [Generator.cpp](https://github.com/Encryqed/Dumper-7/blob/main/Dumper/Generator.cpp#L82). Send the resulting GObjects dump then.

**Comment by Fischsalat** [comment]
Put a print statement in there and send the console output afterwards. I want to see if they change the name of some member, or if there's something else wrong.
```c++
int32 SearchStart = ObjectArray::FindClassFast("Object").GetStructSize() + ObjectArray::FindObjectFast<UEStruct>("URL", EClassCastFlags::Struct).GetStructSize();

UEClass LevelClass = ObjectArray::FindClassFast("Level");

for (UEProperty Property : LevelClass.GetProperties())
    std::cout << "Property: " << Property.GetName() << std::endl;

int32 SearchEnd = ObjectArray::FindClassFast("Level").FindMember("OwningWorld").GetOffset();
```

**Comment by NyanAlex** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/85035681/6540c968-b9cd-4bb0-a669-62d02a9961e7)

**Comment by Fischsalat** [comment]
Ok, this is strange, it doesn't find ULevel for some reason. I think you **do** need to send me an object dump (as described above).

**Comment by NyanAlex** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/85035681/0e8539ef-840b-4579-a0b0-d6be96d6a66c)
GObjects Dump empty

**Comment by Fischsalat** [comment]
in that case try putting the call to `DumpObjects` right before the line that's crashing (in `FindLevelActorsOffset`).

**Comment by NyanAlex** [comment]
[GObjects-Dump.txt](https://github.com/user-attachments/files/15752857/GObjects-Dump.txt)

**Comment by Fischsalat** [comment]
BRUH! Just change "Level" to "level" and you should be good. What is wrong with these gamedevs???
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/69ecf804-afa6-4d22-b9ae-60d8647fbc05)

**Comment by NyanAlex** [comment]
Thank you very much!

**Comment by TimmieDevelops** [comment]
> Thank you very much!

just a thank you that's crazy how he say what's wrong with you

**Comment by Fischsalat** [comment]
what?

**Comment by Fischsalat** [comment]
I also pushed a fix to the Main and BP-Decompiler branches.

**Comment by NyanAlex** [comment]
> > Thank you very much!
> 
> just a thank you that's crazy how he say what's wrong with you


dude, why did you react to common politeness like that?

**Comment by Fischsalat** [comment]
I've noticed that this entire issue could've been avoided if I just used `GetClass()` on the ULevel instance I already have. This way there wouldn't have been any `FindObject` calls, and we would not have need to worry about the name starting capital or lowercase.
