### ISSUE TITLE
Access Violation Level-level fix

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#150]
even after today's fixes in the code, the game crashed when trying to make a dump, but I found a solution!

Fix: Change in CppGenerator.cpp - CppGenerator::InitPredefinedMembers()
```
PredefinedElements& ULevelPredefs = PredefinedMembers[ObjectArray::FindClassFast("Level").GetIndex()];
```
To
```
UEClass lvl = ObjectArray::FindClassFast("Level");
if (!lvl) {
	lvl = ObjectArray::FindClassFast("level");
}
PredefinedElements& ULevelPredefs = PredefinedMembers[lvl.GetIndex()];
```

**Comment by Fischsalat** [comment]
True I forgot about that part. Fixed it on Main/BP-Decompiler too.
