### ISSUE TITLE
Access violation, UE 4.27 - Killer Klowns From Outer Space

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#152]
![Снимок экрана 2024-06-11 224415](https://github.com/Encryqed/Dumper-7/assets/85035681/340f3778-ddc8-4bb8-b87d-6b4c94711fce)
![Снимок экрана 2024-06-11 224348](https://github.com/Encryqed/Dumper-7/assets/85035681/4c3e5282-d155-4644-951d-919e506c6a0e)

**Comment by Fischsalat** [comment]
You're not null-checking the actor before calling the function.
