### ISSUE TITLE
Using The SDK

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#157]
In Using The SDK - Static Functions

Change 
```
SDK::FName MyNewName = SDK::UKismetStringLibrary::Conv_StringToName("DemoNetDriver"); //error!
```
To
```
SDK::FName MyNewName = SDK::UKismetStringLibrary::Conv_StringToName(L"DemoNetDriver");
```

**Comment by Vincent1232** [comment]
Listen bro I don't think DemoNetDriver don't exist on your SDK maybe try to use NetDriver and see what it takes you. 🙃

**Comment by Fischsalat** [comment]
@Vincent1232 seriously just stop replying to anything on this repository. You yourself have given some of the most retarded responses and issues on this repo. 

@NyanAlex you're right, forgot that L.
