### ISSUE TITLE
7.40 dump issue

### ISSUE THREAD

**Issue by Vincent1232** [Encryqed/Dumper-7#16]
![image](https://user-images.githubusercontent.com/98626520/235332664-77311e48-9986-492e-9536-14d9039fb4a7.png)

LoginId:27413c3e4e9d0c9a67cdc781c4707607
EpicAccountId:30fe06b94fce41e1a771994cd923a40d

Unhandled exception

Dumper_7!ObjectArray::FindObjectFast<UEClass>() [C:\Users\e\source\repos\Dumper-7-main\Dumper\ObjectArray.cpp:365]
Dumper_7!ObjectArray::GetAllPackages() [C:\Users\e\source\repos\Dumper-7-main\Dumper\ObjectArray.cpp:322]
Dumper_7!Generator::GenerateSDK() [C:\Users\e\source\repos\Dumper-7-main\Dumper\Generator.cpp:36]
Dumper_7!MainThread() [C:\Users\e\source\repos\Dumper-7-main\Dumper\Main.cpp:57]
kernel32
ntdll

**Comment by Fischsalat** [comment]
Are you injecting in the login screen/lobby?

**Comment by Vincent1232** [comment]
Yes

**Comment by Fischsalat** [comment]
then you're doing something wrong as everything works perfectly fine

**Comment by Vincent1232** [comment]
that just stupid
