### ISSUE TITLE
Palia Dump Crashing (SDK Generator for FN)

### ISSUE THREAD

**Issue by VoidPollo** [Encryqed/Dumper-7#161]
Opening an issue as per requested in #130 
![gitt](https://github.com/Encryqed/Dumper-7/assets/5094754/12f2f548-4038-4412-9f79-0ebbd1bdd463)

**Comment by Wimberton** [comment]
Agreed with this heavily. Would be a lifesaver for us!

**Comment by Fischsalat** [comment]
That should be fine as a temporary fix. Did you try freezing the game before injecting?

**Comment by Wimberton** [comment]
> That should be fine as a temporary fix. Did you try freezing the game before injecting?

We have not given that a try. Good idea.
