### ISSUE TITLE
Static Assertion failed with ********* has a wrong offset

### ISSUE THREAD

**Issue by AndrianiP** [Encryqed/Dumper-7#175]
I am pretty sure i followed the instructions and even copy pasted the example code in UsingTheSDK and i am getting 2850 errors. I am aware that in UsingTheSDK file there is a bullet point that says if there are any static inserts errors than read the issues section of the readme, but it does not say how to fix it. Only remotely close thing it says is to make a issues post.

Game i am trying to dump is Tribes of Midgard.

![image](https://github.com/Encryqed/Dumper-7/assets/42726095/da4c413d-39a8-4ece-85b5-1de853d70a2f)

![image](https://github.com/Encryqed/Dumper-7/assets/42726095/6c526f6f-92ef-4202-a5e0-497f912d53f6)

**Comment by Fischsalat** [comment]
It also says to disable/hide intellisense errors, but we see how well that worked...
