### ISSUE TITLE
Doesnt work for Calabiyau

### ISSUE THREAD

**Issue by Spuckwaffel** [Encryqed/Dumper-7#176]

**Comment by Fischsalat** [comment]
We've been unaware of this issue so far. We'll look into it as soon as possible. Please not that there are a lot of requests at the moment and all of our support staff are occupied. You may experience delays longer than usual. We work to our highest standards and hope we'll be able to handle your request swiftly, to your fullest enjoyment. 

Our next free customer service worker is reserved for you.
