### ISSUE TITLE
Suggestion: Have an option to alphabetically sort the header includes in SDK.h (makes it easier to manually include)

### ISSUE THREAD

**Issue by Derjoe123** [Encryqed/Dumper-7#179]
I often find myself not using the entire sdk, but i still like the SDK.h as a single include, so i had changed GenerateSDKHeader to sort the includes before writing them. Maybe other people have a use for this too, so i could create a pull request if wanted.

**Comment by Fischsalat** [comment]
Seems like a weird feature. I don't really see how it's easier to comment/remove several parts of the `SDK.hpp` file, compared to just making a file called `SDKIncludes.hpp` with all of the includes that you need. The only advantage I see for your method is for people who somehow only want all includes starting with a certain letter.

**Comment by Derjoe123** [comment]
For me i like having this, because i want to include a class with the corresponding _structs header, without looking for it. I also think the header is easier to navigate. Like i said it was an improvement for me personally and i thought i could contribute something to this project.

**Comment by Fischsalat** [comment]
But what's the advantage compared to making your own file that includes the stuff you need? I just don't get it why commenting out a bunch of stuff from the SDK.hpp file is better in any way.
