### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by zinx-YT** [Encryqed/Dumper-7#18]
Trying to use FProperty branch on 12.10 but theres missing Border/TextStyle Files
![image](https://user-images.githubusercontent.com/63958372/235489948-0a7015a9-26e7-4a90-a8b4-621945b5db33.png)

**Comment by zinx-YT** [comment]
Issue was fixed on a older commit

**Comment by TimmieDevelops** [comment]
> zinx

same thing happened to me

**Comment by Fischsalat** [comment]
The issue has been fixed in one of the previous commits on the FProperty-Experimental branch.

**Comment by TimmieDevelops** [comment]
Thank you Fishsalat your the best no way!

**Comment by zinx-YT** [comment]
I legit 

> Issue was fixed on a older commit
