### ISSUE TITLE
static_assert  Static assertion failed

### ISSUE THREAD

**Issue by 2875586627** [Encryqed/Dumper-7#181]
static_assert failed: 'Wrong size on ULGUIScaleAdaptation‘
I've tried a lot of things and still can't fix it
![图片](https://github.com/user-attachments/assets/dd216ea3-ff6d-4215-a1fe-9b691937c453)

**Comment by Fischsalat** [comment]
Hm, I'm not even sure if the SDK compiles without the static_asserts, as a lot of names on this game should be in chinese, which the dumper doesn't support yet. 

This is not a fix for assertions failing, but for this one time, try turning assertions off in the Settings.h of the dumper and generate a new sdk. See if that compiles and give me an update please.

**Comment by 2875586627** [comment]
I'm closed，After that, he reported an error ，
![微信图片222](https://github.com/user-attachments/assets/2148d288-f82a-44d1-839a-b11ae662f584)
 But after dumping the CppSDK, I imported it into the VS project and found that it didn't seem to be complete
		/* Adds static_assert for struct-size, as well as struct-alignment */
		inline constexpr bool bGenerateInlineAssertionsForStructSize = false;

		/* Adds static_assert for member-offsets */
		inline constexpr bool bGenerateInlineAssertionsForStructMembers = false;

**Comment by Fischsalat** [comment]
Try again, turning off assertions can't be the cause of the crash.

**Comment by 2875586627** [comment]
Thank you, the project has been successfully produced
