### ISSUE TITLE
Issue with Justification enum in Widget classes that have a Ejustification member aswell as a method that takes a parameter of type EJustification.

### ISSUE THREAD

**Issue by nuntax** [Encryqed/Dumper-7#191]
**Minimalized example**

```cpp
class UWB_Button02_BlurShine_C final : public UUserWidget
{
public:
	EJustification                                EJustification;                                    // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
public:
	void UpdateJustification(EJustification Param_EJustification);


public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Button02_BlurShine_C">();
	}
	static class UWB_Button02_BlurShine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Button02_BlurShine_C>();
	}
};
```
Classes like this have the Problem that the EJustification member has the same name as its type.
UpdateJustification takes a parameter of EJustification and therefore throws an error since the compiler doesnt know that the type and not the member is meant.
Its an easy manual fix by just changing
 `void UpdateJustification(EJustification Param_EJustification);`
 to 
`void UpdateJustification(SDK::EJustification Param_EJustification);`
But could maybe still be fixed in the future.

**Comment by Fischsalat** [comment]
Yea, this is the same as issue as at the bottom of #186, but I'll keep this one as it's more compressed and clearer.

Could you send the game name please?

**Comment by nuntax** [comment]
Game is AimGods. Not available for download anymore tho

**Comment by Fischsalat** [comment]
not fixed, but well, I don't know a fix
