### ISSUE TITLE
Padding Question/Discussion

### ISSUE THREAD

**Issue by warflash** [Encryqed/Dumper-7#192]
Hey, first off big thanks for maintaining and creating this tool!
I have more of a question instead of an issue but wasn't sure where else to post.
I dumped the SDK for a game which overall worked perfectly, however the "Character" class generated which seems to be the main class everything is based on has a ton of padding fields. (Multiple fields with > 1k bytes and one with 32k)
All I'm trying to do is figure out how that character is linked to the datatable rows in the paks and I can't find any fields for ids anywhere in the SDK. Same for things like HP values. Those are shown in the UI  tho. So my guess would be that those are hidden in a padding field?

The question now, since I'm pretty inexperienced: Is it expected to not have any links to datatables in character/pawn classes or is that a remnant of all the padding?

Created a gist with the class I'm refering to here: https://gist.github.com/warflash/86a99e71592f984a9141d6061bacf180

I know this might not be the best place for questions but like I said wasn't sure where else to post, hope that's fine!

**Comment by Fischsalat** [comment]
Asking a question isn't a problem. 

Padding can be one of two things, implicitly generated padding from the compiler between members of different alignment. A pair of (bool, double) has 0x7 bytes after the bool, so the double is 0x8 aligned. 
The second type of padding is class members for which there is no information available in UnrealEngine's reflection system. Those are all of the members in UE which don't have a UPROPERTY macro above them.
\
![image](https://github.com/user-attachments/assets/f1b15389-a4b3-4df5-b236-4769a0401462)
In this case the `DefaultPhysicsVolume` would be in the SDK and `bAllowDeferredPhysicsStateCreation` would either be Pad[0x1] or part of a bigger block of padding.

Some games decide to make their health variables reflected, others don't. I guess in your case you just need to search with CheatEngine, or look at the entire class with Reclass. For Datatable entries it's pretty much the same. You can also try looking for structs that inherit from `FTableRowBase`.
