### ISSUE TITLE
Ready or Not v54936 UWorld offset is invalid 

### ISSUE THREAD

**Issue by gir489returns** [Encryqed/Dumper-7#194]
They upgraded the engine from 4.27.2 to 5.3.2.

The SDK generator claims UWorld is here:

constexpr int32 GWorld            = 0x0899E910;

Which in IDA is this:

qword_14899E910

But it's only ever referenced once, in this function:

```
__int64 *sub_14355DB70()
{
  qword_14899E910 = 0i64;
  (*(void (__fastcall **)(__int64, const wchar_t *, const wchar_t *, _QWORD))(*(_QWORD *)v2 + 104i64))(
    v2,
    L"dumpticks",
    L"Dumps all tick functions registered with FTickTaskManager to log.",
    0i64);
  atexit(`FTickTaskManager::Get'::`2'::`dynamic atexit destructor for 'SingletonInstance'');
  Init_thread_footer(&dword_14899E930);
  return &qword_14899E8E0;
}
```

However, GWorld is actually here:

.data:00000001489A1798 GWorld          dq ?                    ; DATA XREF: sub_142632AD0:loc_142632B77↑r

The SDK-generator claims:

*	- THe 'GWorld' offset is not used by the SDK, it's just there for "decoration", use the provided 'World::GetWorld()' function instead

However, my calls to UWorld::GetWorld() seem to dictate otherwise:

// Predefined Function
// Gets a pointer to the current World of the GameViewport

```
class UWorld* UWorld::GetWorld()
{
	if constexpr (Offsets::GWorld != 0)
		return *reinterpret_cast<UWorld**>(InSDKUtils::GetImageBase() + Offsets::GWorld);

	if (UEngine* Engine = UEngine::GetEngine())
	{
		if (!Engine->GameViewport)
			return nullptr;

		return Engine->GameViewport->World;
	}

	return nullptr;
}
```

If I comment out the constexpr check, it works again.

**Comment by gir489returns** [comment]
Is it really worth switching to a single pointer dereference? Engine -> Viewpord -> World is extremely reliable. I can't imagine the runtime cost of dereferencing 3 pointers is that much.

**Comment by Fischsalat** [comment]
You did read the same message I wrote, right? Because at no point am I talking about the performance of `UWorld::GetWorld()`.

> To get "GWorld" I'm just scanning memory till I find mem that contains a pointer to the current world. I guess I could see how many occurrences I get, count the references for each one and use the one with the most refs.

In the dumper.

**Comment by gir489returns** [comment]
> You did read the same message I wrote, right? Because at no point was I talking about the performance of `UWorld::GetWorld()`.
> 
> > To get "GWorld" I'm just scanning memory till I find mem that contains a pointer to the current world. I guess I could see how many occurrences I get, count the references for each one and use the one with the most refs.
> 
> In the dumper.

It's more of asking why, not how. Why use this offset address?

**Comment by Fischsalat** [comment]
> The reason I decided to use "GWorld" was because there is no game viewport on servers, so Get world would always fail there.

**Comment by gir489returns** [comment]
> > The reason I decided to use "GWorld" was because there is no game viewport on servers, so Get world would always fail there.

Ah yeah, that makes sense. Since it's now using an offset, should it also get an InitManually function?

**Comment by Fischsalat** [comment]
Nah, there's nothing to initialize.
