### ISSUE TITLE
Wrong FName::ComparisonIndex type?

### ISSUE THREAD

**Issue by gamerbross** [Encryqed/Dumper-7#199]
I dont know exactly if this was changed later and hasnt been like this always, but in my UE code (pretty recent), value of `FNameEntryId` is a uint32 and not int32.
![image](https://github.com/user-attachments/assets/4637e0e8-1ecc-4b6c-9068-7328f986ccab)
![image](https://github.com/user-attachments/assets/665779cb-8bb4-4944-8af3-bf32b6d86c62)

**Comment by Fischsalat** [comment]
It's int32 on versions before 4.23 and was changed to uint32 when they introduced FNamePool.

**Comment by Fischsalat** [comment]
fixed
