### ISSUE TITLE
skunked

### ISSUE THREAD

**Issue by MagmaDev12** [Encryqed/Dumper-7#20]
fix yo goddamn sdk dumper!!!! 12.41 crashg!!!!!!!!! omg so bad
😡😡😡😡😡😡

**Comment by MagmaDev12** [comment]
wow so rude this is unacceptable i bet u like obama hamburger sussy balls!!!

**Comment by zinx-YT** [comment]
sir!

**Comment by MagmaDev12** [comment]
no
+

**Comment by zinx-YT** [comment]
;(

**Comment by MagmaDev12** [comment]
@i sing for you play wii mii theme 10h

**Comment by Fischsalat** [comment]
shut the fuck up, neither of you kids are funny
