### ISSUE TITLE
Static Assert / Bad Types

### ISSUE THREAD

**Issue by qey32** [Encryqed/Dumper-7#200]
Hey sorry to make an issue for this knowing that am maybe doing everything wrong but if someone can explain me how the dumper works and if i need to like fix all the types / structs / errors cause I found a guy who just dropped the sdk and started using it thanks if you read this message and sorry for losing your time.

![image](https://github.com/user-attachments/assets/685dd5d3-b6b8-4d46-a61e-af8e74a6874e)
![image](https://github.com/user-attachments/assets/7a62644e-dff8-4c49-b150-189af43c2348)

**Comment by Fischsalat** [comment]
I've never tried compiling the SDK with clang, but I guess it's having some problem with non-type template arguments. Make sure you're on the latest C++ version, clang should accept that code.

**Comment by qey32** [comment]
I was using gcc for the screens

**Comment by qey32** [comment]
and am also having undefined vars like `NumInlineElements` , `MaxElements` ect
