### ISSUE TITLE
Suicide Squad, AppendString Access Violation

### ISSUE THREAD

**Issue by xIntrinsic** [Encryqed/Dumper-7#204]
![image](https://github.com/user-attachments/assets/5edbd4d2-69b1-4570-a4a5-3669b76a90f9)

**Comment by Fischsalat** [comment]
just change `FName::Init()` to `FName::Init(true)` to force GNames and you should be good.

**Comment by xIntrinsic** [comment]
After doing the suggested i get the following 

![image](https://github.com/user-attachments/assets/c5ac5bef-10aa-4f42-8362-26bb85031986)

**Comment by Fischsalat** [comment]
Well that sucks. Is there any way I can access the game to debug it?

**Comment by xIntrinsic** [comment]
are you EU or US ?

**Comment by Fischsalat** [comment]
eu

**Comment by xIntrinsic** [comment]
I could just buy a steam key and the  send it you on discord or something?

**Comment by Fischsalat** [comment]
Works for me. Discord `fischsalat`

**Comment by Fischsalat** [comment]
Fixed on the [ObjectArrayLayout-UObjectFix](https://github.com/Encryqed/Dumper-7/tree/ObjectArrayLayout-UObjectFix) branch.
UObject::Name was moved in front of UObject::Class, which the generator didn't handle correctly.

I will close this issue once I merged the branch into main.

**Comment by xIntrinsic** [comment]
Wow thanks for the fix

**Comment by Fischsalat** [comment]
merged it into main.
