### ISSUE TITLE
[EDITOR ONLY] Missing `FField::MetaDataMap`

### ISSUE THREAD

**Issue by gamerbross** [Encryqed/Dumper-7#210]
![image](https://github.com/user-attachments/assets/f57cedb9-12a6-4742-b95a-705e2bd35903)
*Engine\Source\Runtime\CoreUObject\Public\UObject\Field.h:750*

Idk if editor stuff is supported by dumper-7 but posting it anyway in any case

**Comment by Fischsalat** [comment]
It's not supported and I'm not sure if I want to support it. The class itself is still fine, as `MetaDataMap` comes after all of the other members. There's also no case in which `sizeof(FField)` matters, as far as I know.
