### ISSUE TITLE
UE 4.5.3 support

### ISSUE THREAD

**Issue by Kein** [Encryqed/Dumper-7#217]
Looks like there are some changes in struct layouts so it crashes on 5.4.x

**Comment by Fischsalat** [comment]
1. Your title says `4.5.3`
2. some changes in struct layouts?
3. That's no where near enough information to do anything.

I don't know what game you're talking about, I don't know what you've tried, I don't know if you've even attempted debugging the crash, I don't know anything. 

What am I supposed to do with this? The generator works fine on UEFN, which is UE5.5, it works fine on other FN versions which were 5.4 and it works fine on Vein which is also 5.4. 

If you got an issue with a certain game, make a reasonable github issue with useful information. I'm not magic.

**Comment by Kein** [comment]
It wasnt hard to figure out that it was a type, wasn't it? `5.4.3` of course.

>  5.4 and it works fine on Vein which is also 5.4.
Which 5.4, though? There is 3 patch versions in the lineup.

**Comment by Fischsalat** [comment]
Well, attach the debugger and give me some more information. Like what game is that? Where's it crashing? What's the callstack?

Create a new issue with all the informations.

**Comment by Kein** [comment]
Hey sorry, was busy.
The game is The Isle.
It is built as Client, Shipping configuration.

It crashes at:
```
Started Generation [Dumper-7]!
Dumper-7 by me, you & him
Searching for GObjects...
Found FChunkedFixedUObjectArray GObjects at offset 0x9176f00
Found 'FNamePool GNames' at offset 0x90BFB40
Found FName::AppendString at Offset 0x11138D0
```

*@UnrealTypes.cpp*
![image](https://github.com/user-attachments/assets/54da23e0-ce12-44d5-86f5-2c462765424c)

**Comment by Fischsalat** [comment]
Are there any specific args to launch the server so it doesn't close after 5sec.? 

It stopped working recently and clearing the localappdata folder didn't help?

**Comment by Kein** [comment]
Are you talking about specific server or vanilla UE build? If latter, I think you need to pass the map as an argument i.e. `/Game/Maps/Dummy_Map -log`

**Comment by Fischsalat** [comment]
The major offsets will be wrong, so why would you dump the client when you could also just dump the server? 

Also I was asking specifically about TheIsle.

**Comment by Fischsalat** [comment]
> But the crash in question isnt with the server but with Client build.

Are you sure tho?
![image](https://github.com/user-attachments/assets/7f4c53f7-e8ec-46f5-9226-8d0a43937374)

**Comment by Kein** [comment]
> Are you sure tho?
Yes, I've just synced with latest git and tried again - crashes exactly as in the OP.

**Comment by Fischsalat** [comment]
Use the unicode-names branch, that's the one i tested it with.

**Comment by Kein** [comment]
Similar crash:
![image](https://github.com/user-attachments/assets/03928a55-af10-45e2-acdc-b3b8bdad9c72)

**Comment by Fischsalat** [comment]
When does that crash occure? I've tried before and it crashed once but worked on the 2nd try. Also maybe freeze the game before dumping, might help.

**Comment by Kein** [comment]
Right after injection. It crashes immediately so 2nd injection is useless.
Suspeding process does not help.

**Comment by Fischsalat** [comment]
That doesn't make any sense, are you sure you're investing into the right process? Sometimes there's two processes called TheIsle-Win64-Shipping.exe.

**Comment by Kein** [comment]
Yes, I'm 100% sure, I know where and how to inject. I dont even run it via main binary because it bootstraps EAC which wont le me inject.
The crash is really weird but it is consistent. May be it finds to find some of the offsets/addresses? It thinks it is valid so calling it causes access vioation

**Comment by Fischsalat** [comment]
Change the IDs in EACs `Settings.json`. If these files don't work for you it is 100% a user-error. I've dumped the game just fine 1min. ago. 

The dll shouldn't differ from the UnicodeNames branch tho. Obviously you need to remove the .txt ending, I had to add that to get around githubs stupid restrictions.
[Dumper-7.dll.txt](https://github.com/user-attachments/files/16922055/Dumper-7.dll.txt)
[Dumper-7.pdb.txt](https://github.com/user-attachments/files/16922056/Dumper-7.pdb.txt)

**Comment by Kein** [comment]
Crashes at `AppendString` again.

> Change the IDs in EACs Settings.json

What for? I dont run it under EAC.

>  If these files don't work for you it is 100% a user-error. 

If it is a user-error, where would it be then? I'd love to address it but I just dont see where - I start the game until I see title menu and then inject the DLL via CE, which I use for every manual injection.

**Comment by Fischsalat** [comment]
well, just start the game with the anticheat bootstrapper after changing the ids, try another injector, do whatever. I don't know what else to do

**Comment by Kein** [comment]
What changing the ID does?

**Comment by Fischsalat** [comment]
I tested it on the latest hordtesting branch. 

And with incorrect IDs in EAC's settings.json file it does start the game but never attaches to it, so you can use normal load-library injection without issues.

**Comment by Kein** [comment]
Yeha, it makes no difference.

**Comment by Kein** [comment]
Just for the sake of it, I tested on 5.1, 5.2 and 5.3 - dumps just fine.
5.4.x crashes it.

**Comment by Fischsalat** [comment]
well, I can't really help you if it works for me. try overwriting gnames or tracking down the error

**Comment by Kein** [comment]
> well, I can't really help you if it works for me. try overwriting gnames or tracking down the error

As in offset for GNames? If there some simpleish way for me to validate offset was found correctly with the default setup? Something I can look for?

**Comment by Fischsalat** [comment]
well, the offsets are printed to the console, you can verify them in ida

**Comment by Fischsalat** [comment]
I told you last time, it works for me and I'm using the same code from the same repo. Attach VS to the game and inject in debug.

**Comment by Kein** [comment]
And I already posted it twice
https://github.com/Encryqed/Dumper-7/issues/217#issuecomment-2336480153

Thing is, ass offsets are correct, it is some internal mechanics of Dumper that lead to crash under specific circumstances in specific environments, hence why I offered to provide a dump. Note that it started happening since August 2024, any version before that worked fine for me on any UE <5.4.x
