### ISSUE TITLE
SDK::UWorld::GetWorld() returning "null"

### ISSUE THREAD

**Issue by worldtoscreen** [Encryqed/Dumper-7#218]
Hello,

I have started to use Dumper-7 and have encountered an issue - when calling SDK::UWorld::GetWorld(), it returns 'null' and takes a very long time to actually find a world (when calling it in a loop).

Are the offsets incorrect, or is this a Dumper-7 issue?

**Comment by Fischsalat** [comment]
Well, if it finds something for GWorld it is going to use that offset (there is not 100% guarantee that's GWorld), else it's going to us the world in the game viewport.

Try commenting out the first if statement in GetWorld

**Comment by worldtoscreen** [comment]
Commenting out the first if statment in the GetWorld() method worked perfectly. You're awesome!
