### ISSUE TITLE
static_assert failed

### ISSUE THREAD

**Issue by HereForYourCode** [Encryqed/Dumper-7#219]
Game: borderlands 3
![error](https://github.com/user-attachments/assets/1065bd23-108a-44a8-9978-3c4e719ae98c)

followed the guide and im still getting errors. I also tried going over your past issues but they dont seem applicable to my situation.
[CppSDK.zip](https://github.com/user-attachments/files/16567875/CppSDK.zip)
(I can provide other files if needed but entire zip was too large so im just sending the CppSDK)

**Comment by HereForYourCode** [comment]
note: in loading screen it generated the sdk fine but when I load into the game it crashes and i get memory violation errors.

**Comment by Fischsalat** [comment]
Maybe send a picture of UObject if it says "UObject has wrong alignment"

**Comment by HereForYourCode** [comment]
I did send the cppSDK it generated so you can check it out, but I went into the CoreUObject_classes.hpp and I get this:
![eeee](https://github.com/user-attachments/assets/a67d6d8c-66a1-4d0a-a2ca-335d764e4b05)
(name: sea of thieves???). Maybe its because I didnt run the sdk dumper when I loaded into the game and instead only in the loading screen. But I can't do much about that since it crashes when i try to dump the game when ive loaded in.

**Comment by HereForYourCode** [comment]
![ccc](https://github.com/user-attachments/assets/98c1a19c-eca6-463e-a2a4-6bab904d8a2e)
here is the entire object class (deleted previous comment because I think I sent wrong image). Maybe its because i run the dumper in the loading screen and not in the actual game (problem is it crashes when i run the dumper when i load into game) 
![errorrrss](https://github.com/user-attachments/assets/d6feb97d-a619-4895-bbca-fe6ee10ee1ef)
more static errors that dont show up in the error list but are visible in the project.

**Comment by Fischsalat** [comment]
change the asserted alignment to 0x8, 0x1 is a bug, keep this ticket open, i need to fix this

**Comment by HereForYourCode** [comment]
you are the goat bro it actually compiles now.... THX <3

**Comment by worldtoscreen** [comment]
Hey, did you ever fix the access violation?

I can't do this either.
