### ISSUE TITLE
'SDK::OnlineSubsystemUtils::UOnlineEngineInterfaceImpl': 'class' type redefinition

### ISSUE THREAD

**Issue by jean1710** [Encryqed/Dumper-7#220]
Getting this issue when using #include "SDK.hpp" in my project.

I hope i'm not missing anything... 
![image](https://github.com/user-attachments/assets/992076b6-47e8-45a2-abcf-17b99326ebe2)

The project folder can be downloaded here: [https://www.dropbox.com/scl/fi/1746i05m0nyhtexgrb0hh/Project1.zip?rlkey=9bzrnazoes2npbyq86gp3fu4a&st=40rhbgvm&dl=0](url)

Hope it's not a stupid error from my side .

**Comment by jean1710** [comment]
Probably important to note that this is for ark survival ascended.

**Comment by Fischsalat** [comment]
Just rename one of them to number 2 and you're fine.
