### ISSUE TITLE
static_assert failed

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#221]
A bunch of failed static asserts:
![devenv_vJ945n3nLh](https://github.com/user-attachments/assets/d89b53f9-d7bd-428d-9f3b-b49038e752e8)

[5.2.1-0+UE5-Polaris.zip](https://github.com/user-attachments/files/16640971/5.2.1-0%2BUE5-Polaris.zip)

Going to fix the paddings by hand for now, I guess.

After looking into it, it appears the problem is in `alignas` in classes. Once you do `alignas(0x10)` in any of the base classes, consecutive classes don't put first members on 0x8 offsets, which causes sizes and offsets of everything to be wrong.

**Comment by KulaGGin** [comment]
Yeah, after investigating further, I just removed all `alignas(0x10)`, and then also all the tests `static_assert\(alignof\(.*` and `static_assert\(sizeof\(.*` and now it seems to be compiling.

And because all the `static_assert(offsetof(` tests are passing, we know that all the offsets for all the properties are correct, indeed.

**Comment by Fischsalat** [comment]
Great job not turning  off intellisense errors as instructed in the issues tab of the readme and the setup tab of UsingTheSDK. 
The original sdk compiles just fine without removing or modifying anything. 
![image](https://github.com/user-attachments/assets/c8ee7f9a-bada-412c-ab30-5896921dc73f)
