### ISSUE TITLE
Crash on Inject For ARK 1

### ISSUE THREAD

**Issue by w0rst-nitemare** [Encryqed/Dumper-7#222]
Game is ARK: Survival Evolved
![image](https://github.com/user-attachments/assets/d38e775c-cf19-40ea-9c9d-c79c1d231449)

**Comment by w0rst-nitemare** [comment]
![image](https://github.com/user-attachments/assets/91b0466d-7449-4998-8538-eaf4ddb04cfc)

**Comment by Fischsalat** [comment]
Cool? Any offsets that aren't found? Are the offsets that are found valid? How about checking stuff yourself and giving me some information?

**Comment by Dave5051337** [comment]
same issue here it crash on inject 

![image](https://github.com/user-attachments/assets/50fd35d7-cdd2-476d-8fbc-bb9fd09939ad)

**Comment by Fischsalat** [comment]
hardcode the offset
![image](https://github.com/user-attachments/assets/edb4bef6-993f-47bd-aeac-46f2b438f86e)

**Comment by Dave5051337** [comment]
how do i do that?

**Comment by Fischsalat** [comment]
reverse it with reclass and then set it in Off::Init()

**Comment by Dave5051337** [comment]
got it thx!
Off::Property::PropertyFlags: 0x38
