### ISSUE TITLE
Access violation, ark uwp

### ISSUE THREAD

**Issue by DKMtomy** [Encryqed/Dumper-7#225]
![image](https://github.com/user-attachments/assets/377b3119-e590-46d5-8114-e86e387499f9)

this debugger shows it in "FName::Init(bool bForceGNames)"

```cpp
ToStr = [](const void* Name) -> std::string
{
	thread_local FFreableString TempString(1024);

	AppendString(Name, TempString); // <- here is where the error happens

	std::string OutputString = TempString.ToString();
	TempString.ResetNum();

	return OutputString;
};
```

the error is "Exception thrown at 0x0000000000000000 in ShooterGame.exe: 0xC0000005: Access violation executing location 0x0000000000000000.
"

**Comment by Fischsalat** [comment]
It didn't find GNames or AppendString. Just use CheatGear for ark.
