### ISSUE TITLE
Crash in injection Atach imagen

### ISSUE THREAD

**Issue by cutelake123321** [Encryqed/Dumper-7#226]
Hi, thanks for this tool, it's great, but I have a problem with this mk1 game
When I inject it stays in this section and doesn't continue, then the game crashes. I'm attaching the debugging information, I hope it can be fixed.
![2211](https://github.com/user-attachments/assets/65a12c3f-f063-4cdd-855c-7a7827937216)

**Comment by Fischsalat** [comment]
Put this snippet of code into `FindElementSizeOffset()` and send the output:
```c++
for (UEProperty Prop : Guid.GetProperties())
    std::cout << "Guid->" << Prop.GetName() << std::endl;
```

![image](https://github.com/user-attachments/assets/976390f2-0051-4a5f-9ee3-6418ab46bcf0)

**Comment by cutelake123321** [comment]
> Put this snippet of code into `FindElementSizeOffset()` and send the output:
> 
> ```c++
> for (UEProperty Prop : Guid.GetProperties())
>     std::cout << "Guid->" << Prop.GetName() << std::endl;
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/64608145/362687039-976390f2-0051-4a5f-9ee3-6418ab46bcf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzYyODUsIm5iZiI6MTcyNDkzNTk4NSwicGF0aCI6Ii82NDYwODE0NS8zNjI2ODcwMzktOTc2MzkwZjItMDA1MS00YTVmLTllZTMtNjQxOGFiNDZiY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEyNTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYTFkZTQyMTAxZGRjMTYwYzBkOWYwOTk0NzRjM2E1NzdmZTdiNWM2NTMwN2Q1OWQxYjRjYjc2YTc4NjQxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZEuda1SX4U7JciYbeuaFUQ_x9A-Dy8fkfl-vwxfqbkE)

Hey thanks for the quick reply, I added the "for" to the snipper code and this is what I got

![yy22](https://github.com/user-attachments/assets/ca931b45-404c-461b-875a-59687fd9afd3)

**Comment by Fischsalat** [comment]
They have to be fucking trolling. Why is the 'b' lowercase??? To fix it either replace the capital 'B' with lowercase 'b' or with 'D'.
![image](https://github.com/user-attachments/assets/9ae9a7ae-72e3-4dce-9f09-fb40cb41727d)

**Comment by cutelake123321** [comment]
changing it to "b"
![b](https://github.com/user-attachments/assets/821cd67d-2971-4419-9ba5-3aa60ce05b43)

**Comment by cutelake123321** [comment]
any update?

**Comment by Fischsalat** [comment]
literally the exact same fix as before. Please just look at the stack-frame and the code.

**Comment by cutelake123321** [comment]
> literally the exact same fix as before. Please just look at the stack-frame and the code.

Thanks for answering and helping me, friend, but I'm lost, what should I change now?

**Comment by Fischsalat** [comment]
![Screenshot_2024-08-31-14-55-26-38_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/aefe197b-effe-4afd-a27e-d29abf600174)

Bruh

**Comment by cutelake123321** [comment]
> ![Screenshot_2024-08-31-14-55-26-38_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://private-user-images.githubusercontent.com/64608145/363414737-aefe197b-effe-4afd-a27e-d29abf600174.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDkyNTYsIm5iZiI6MTcyNTEwODk1NiwicGF0aCI6Ii82NDYwODE0NS8zNjM0MTQ3MzctYWVmZTE5N2ItZWZmZS00YWZkLWEyN2UtZDI5YWJmNjAwMTc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MmQ4MTY4NGZjNmYyMTc3YTYxNmZhNWEyMDE5NmRkNjk1YzQ0MWJiYmI5MGUyOTUzOTE1OWE5YTQwY2ZjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RWDfeRCT2xo8P8cL09R6vn7i6JjriyG5yCfEAGiuEiw)
> 
> Bruh

I did what you told me on the other line
changed the "B" to "b" and same error

I also changed the "b" to "d" and same error

here are images
if you can be more specific as you did at the beginning of the message it will be of great help to resolve quickly

![2244](https://githu
![ss2](https://github.com/user-attachments/assets/52ef147f-1cff-4733-b930-bf52d93c2e8b)
b.com/user-attachments/assets/96bc2c1e-8436-4b6b-a4da-9f888b6e42ee)
![2024-08-31 10_45_10-Dumper-7 (Depuración) - Microsoft Visual Studio](https://github.com/user-attachments/assets/649d4c7e-7a57-4310-bf1f-b37596f81481)

**Comment by Fischsalat** [comment]
well, do the same in that function
```c++
for (UEProperty Prop : Whateverclass.GetProperties())
    std::cout << "Whateverclass->" << Prop.GetName() << std::endl;
```
