### ISSUE TITLE
The game crashes after injection

### ISSUE THREAD

**Issue by leekinger** [Encryqed/Dumper-7#227]
The game is SNOWBREAK on Steam
![1](https://github.com/user-attachments/assets/64169ab1-6970-4378-91ca-1d4180454cb4)

**Comment by Fischsalat** [comment]
overwrite GNames or AppendString

**Comment by leekinger** [comment]
How to operate?

**Comment by Fischsalat** [comment]
readme

**Comment by leekinger** [comment]
How to find the offset of AppendString？

**Comment by Fischsalat** [comment]
read tutorials for that. This is not the purpose of issues on github.
