### ISSUE TITLE
nullptr checks

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#228]
Is it possible to add nullptr checks at the SDK level? just curious

**Comment by Fischsalat** [comment]
for what? what the fuck are you talking about?

**Comment by NyanAlex** [comment]
![image](https://github.com/user-attachments/assets/473cd9f5-84a3-43ed-af0a-d5c0cc600cb1)
about this

**Comment by NyanAlex** [comment]
nvm, sorry
