### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by nisanb** [Encryqed/Dumper-7#229]
Was following the readme, but I can't seem to compile.
What am I missing?

Visual studio 2022.

Tried using this SDK:
https://www.unknowncheats.me/forum/downloads.php?do=file&id=45627

![image](https://github.com/user-attachments/assets/e4362dce-a678-4880-9a6b-5ca7299ea0e9)

![image](https://github.com/user-attachments/assets/a71978c6-85c7-4c1a-a1bb-773a76169b95)
![image](https://github.com/user-attachments/assets/8cf6cacc-df7f-46d3-8b3b-26e672ffa2b5)

![image](https://github.com/user-attachments/assets/c3a6b38e-9314-4fde-863e-33ddc07ac9dc)

**Comment by nisanb** [comment]
![image](https://github.com/user-attachments/assets/45236dd6-1605-45a6-beb7-50c638b81e6c)

**Comment by nisanb** [comment]
![image](https://github.com/user-attachments/assets/0a61d47e-89c8-4add-b1f6-5f66f74828f9)

Lots of compilation errors when I try to just import "SDK.hpp"

**Comment by Fischsalat** [comment]
just fix that enum error, that should resolve the rest. I fucking hate it that Windows.h defines enough macros to fuck every 2nd sdk.

Gotta love unscoped macros.

**Comment by nisanb** [comment]
What is the error here though?
I've tried changing RELATIVE to something else (or remove it) but I keep getting compilation errors.

**Comment by Fischsalat** [comment]
Well, the preprocessor replaces all occurrences of macros with the value they are defined as. So the compiler  sees
```c++
enum class EPositionType : uint8
{
    FREE                       = 0,
    2                             = 1,
    EPositionType_Max = 2,
};
```

If you still get errors after changing RELATIVE to something else there's a 2nd error somewhere.

**Comment by nisanb** [comment]
I get endless errors I don't even know where to start with this SDK...
Free on discord for quick look?

**Comment by Fischsalat** [comment]
Can you try dumping the SDK yourself and then send the resulting folder (the entire folder that has the same name as the GameName)? Thanks.

**Comment by Fischsalat** [comment]
.

**Comment by nisanb** [comment]
I did and it’s working, thank you!
________________________________
