### ISSUE TITLE
SoT Crashing when calling PackageManager::Init();

### ISSUE THREAD

**Issue by Skreamex** [Encryqed/Dumper-7#235]
Hello, I'm trying to dump Sea Of Thieves SDK, and Im getting crashes
I set Off::InSDK::NameArray::GNames to **0x83F1BE8** what I got from this sig 
`find_pattern("", "48 8b 3d ? ? ? ? 48 85 ff 75 3c");`
And then my game closes and I get bsod

Here is output from console
`Started Generation [Dumper-7]!

Dumper-7 by me, you & him

Searching for GObjects...

Found FFixedUObjectArray GObjects at offset 0x83f5de8

Found FName::AppendString at Offset 0x1D9D6C0

Off::UStruct::Children: 0x38
Off::Field::Next: 0x28
Off::UStruct::SuperStruct: 0x30
Off::UStruct::Size: 0x40
Off::UStruct::MinAlignemnts: 0x44
Off::UClass::CastFlags: 0xC8
Off::UClass::ClassDefaultObject: 0x110
Off::UEnum::Names: 0x40
Off::UFunction::FunctionFlags: 0x88

Off::UFunction::ExecFunction: 0xB0

Off::Property::ElementSize: 0x194
Off::Property::ArrayDim: 0x-1
Off::Property::Offset_Internal: 0x48
Off::Property::PropertyFlags: 0x30
UPropertySize: 0x70

Off::ArrayProperty::Inner: 0x70
Off::SetProperty::ElementProp: 0x70
Off::MapProperty::Base: 0x70

Off::InSDK::ULevel::Actors: 0xA0

Off::InSDK::UDataTable::RowMap: 0x28

PE-Offset: 0x1E74EA0
PE-Index: 0x37

GWorld-Offset: 0x84C22D0

Off::InSDK::Text::TextSize: 0x7FF7
Off::InSDK::Text::TextDatOffset: 0x0
Off::InSDK::Text::InTextDataStringOffset: 0x0

`

**Comment by Skreamex** [comment]
But can I generate structures only? Like UWorld UObject for esp only?

**Comment by Fischsalat** [comment]
You cant
