### ISSUE TITLE
Satisfactory Could not find GNames.

### ISSUE THREAD

**Issue by gir489returns** [Encryqed/Dumper-7#237]
After injecting, the dumper says Searching for Gobjects, followed by 3 could not find GNames, then "Found GName::ToString at Offset 0x0" which it then crashes immediately after. I had to record my screen so I could capture the output it happened so fast.

**Comment by Fischsalat** [comment]
well, overwrite the offset

**Comment by gir489returns** [comment]
I think I see the issue. The dumper expects the game to be in a singular image (GameName-Win64-Shipping.exe for example), however, Satisfactory has them split up in-between multiple different DLLs. 

Game: FactoryGameSteam-FactoryGame-Win64-Shipping.dll
FNamePool: FactoryGameSteam-Core-Win64-Shipping.dll
GNames: FactoryGameSteam-CoreUObject-Win64-Shipping.dll

Supplying the offset doesn't work, because all of them resolve the offset from GetImageBase() which just resolves the base address (and size) of the EXE, not the respective DLLs.

**Comment by Fischsalat** [comment]
I guess the module-name could be passed as an optional parameter. You can implement that for both the automatic and the manual-overwrite if you want to.
