### ISSUE TITLE
There is an issue with 14.60 SDK.

### ISSUE THREAD

**Issue by Vincent1232** [Encryqed/Dumper-7#24]
![image](https://github.com/Encryqed/Dumper-7/assets/98626520/feff6b79-53c0-4915-9dab-9ba80c143c86)

**Comment by Vincent1232** [comment]
I've tried everything to fix the error in the class and struct.

**Comment by Vincent1232** [comment]
I use FProperty-Experimental to dump the SDK.

**Comment by Fischsalat** [comment]
Use the `main` branch and set `Settings::bIncludeOnlyRelevantPackages` to true. If that doesn't help you'll need to remove a few of these error classes.

**Comment by Vincent1232** [comment]
Thank you, Fishsalat. It works. You're the best!

**Comment by Vincent1232** [comment]
also how I generated the C++ SDK also?

**Comment by Fischsalat** [comment]
I don't understand the question. You already generated a c++ sdk.

**Comment by Vincent1232** [comment]
what i'm trying to say is that i'm trying to dump the Fortnite functions into C++ sdk

**Comment by Fischsalat** [comment]
you can't dump native c++ functions

**Comment by Vincent1232** [comment]
K
