### ISSUE TITLE
greed of man

### ISSUE THREAD

**Issue by yuvalperez** [Encryqed/Dumper-7#240]
![image](https://github.com/user-attachments/assets/6f1af51d-f69f-4cdd-8716-d6b838a12bd6)

**Comment by Fischsalat** [comment]
in case you haven't noticed: the function has the same name as some macro from windows, change it

**Comment by yuvalperez** [comment]
oh thx haven't noticed but now i got into does errors 
![image](https://github.com/user-attachments/assets/19a405d9-d65b-44e6-bc2d-e353a790086a)

**Comment by Fischsalat** [comment]
I believe I fixed that on the Unicode-Names branch, test that one please.
