### ISSUE TITLE
Game Name: Devious Path

### ISSUE THREAD

**Issue by xjgames** [Encryqed/Dumper-7#242]
Who has the usmap file for this game?
++UE5+Release-5.4-CL-34507850

**Comment by Fischsalat** [comment]
Generate it yourself

**Comment by xjgames** [comment]
> Generate it yourself

Sorry, I'm not a programmer. Can you send me the dumper_7.dll file

**Comment by Fischsalat** [comment]
Compile the dll and inject it. That's all. You don't need to be a programmer to click two buttons in visual studio.
