### ISSUE TITLE
static_assert failed: "Wrong allignment on UObject"

### ISSUE THREAD

**Issue by stanojevicc** [Encryqed/Dumper-7#245]
The Code:
![image](https://github.com/user-attachments/assets/41ba94aa-5c8a-4d4b-9188-62ee726afa9d)
 
Where it says its an error:
![image](https://github.com/user-attachments/assets/b89759f6-8c5b-4a6c-9006-7e6c028c9b49)

**Comment by Fischsalat** [comment]
either change it to 0x8 or use the Unicode-Names branch
