### ISSUE TITLE
Question On Fortnite Inventory

### ISSUE THREAD

**Issue by Vincent1232** [Encryqed/Dumper-7#255]
Hello, I'm trying to create my SDK, but how can I make it automatically call `ServerExecuteInventoryItem` to pick up an item when users join the server?

**Comment by Encryqed** [comment]
# Not optimal solution?

You could hook process event and check if a player got loaded into the world?
Then you can simply just call the method?

**Comment by Vincent1232** [comment]
> # Not optimal solution?
> You could hook process event and check if a player got loaded into the world? Then you can simply just call the method?

i'm hook it up but it's still didn't auto call the function

**Comment by Encryqed** [comment]
What i mean by hooking ``ProcessEvent`` is that, when you hook it, you can intercept three arguments: 
``UObject* This``, ``UFunction* Function`` and ``Parameters``.

When a player loads into the world, a function like ``World->SpawnActor(Parameters...)`` should be called. Internally, this results in ``ProcessEvent(World, SpawnActor, Parameters...)`` being called. So if you hook ``ProcessEvent``, you can check if the Function name matches and then execute your code.

Here is an example how you could write it: (note: there is probably a better way to do this)

```cpp
void ProcessEventHook(SDK::UObject* This, SDK::UFunction* Function, void* Parameters)
{
    if (Function->GetName() == "SpawnActor") // Replace "SpawnActor" with the actual function that is responsible for loading the actor into the world
    {
        // Execute your code here, for example, calling ServerExecuteInventoryItem.

    }
}
```

**Comment by Vincent1232** [comment]
> hooking `ProcessEvent` is that, when you hook it, you can intercept three arguments: `UObject* This`, `UFunction* Function` and `Parameters`.
> 
> When a player loads into the world, a function like `World->SpawnActor(Parameters...)` should be called. Internally, this results in `ProcessEvent(World, SpawnActor, Parameters...)` being called. So if you hook `ProcessEvent`, you can check if the Function name matches and then execute your code.

so I did what you told me to do it's still not working for some reason

**Comment by Vincent1232** [comment]
> What i mean by hooking `ProcessEvent` is that, when you hook it, you can intercept three arguments: `UObject* This`, `UFunction* Function` and `Parameters`.
> 
> When a player loads into the world, a function like `World->SpawnActor(Parameters...)` should be called. Internally, this results in `ProcessEvent(World, SpawnActor, Parameters...)` being called. So if you hook `ProcessEvent`, you can check if the Function name matches and then execute your code.
> 
> Here is an example how you could write it: (note: there is probably a better way to do this)
> 
> ```c++
> void ProcessEventHook(SDK::UObject* This, SDK::UFunction* Function, void* Parameters)
> {
>     if (Function->GetName() == "SpawnActor") // Replace "SpawnActor" with the actual function that is responsible for loading the actor into the world
>     {
>         // Execute your code here, for example, calling ServerExecuteInventoryItem.
> 
>     }
> }
> ```

```c++
		if (Function->GetName() == "ServerExecuteInventoryItem")
		{
			AFortPlayerController* InController = (AFortPlayerController*)Object;
			APlayerPawn_Athena_C* InPawn = (APlayerPawn_Athena_C*)InController->Pawn;
			Params::FortPlayerController_ServerExecuteInventoryItem* Params = (Params::FortPlayerController_ServerExecuteInventoryItem*)Parameters;
			for (int i = 0; i < InController->WorldInventory->Inventory.ReplicatedEntries.Num(); i++)
			{
				auto& ItemEntry = InController->WorldInventory->Inventory.ReplicatedEntries[i];
				if (ItemEntry.ItemDefinition)
					InPawn->EquipWeaponDefinition((UFortWeaponItemDefinition*)ItemEntry.ItemDefinition, ItemEntry.ItemGuid);
				LOG("Equipped Item: " << ItemEntry.ItemDefinition->GetName());
			}
			LOG("AFortPlayerController::ServerExecuteInventoryItem");
		}```

**Comment by Vincent1232** [comment]
anyone there???
