### ISSUE TITLE
Generated SDK problems

### ISSUE THREAD

**Issue by matty45** [Encryqed/Dumper-7#26]
Recently built the dumper at commit [2f8743d](https://github.com/Encryqed/Dumper-7/commit/2f8743da6d69036cce44058abfb18b541517a90d)

and these errors have appeared in basic.hpp:
There are duplicate functions in this image and the EClassFlags enum is not in the right place: 
![Error Image](https://i.imgur.com/Amg8mXF.png)

There is also this error inside of CoreUObject_classes.hpp:
![Error Image2](https://i.imgur.com/oqe23sz.png)

**Comment by Fischsalat** [comment]
Yea, my bad, I keep pushing untested commits to main. Could've at least tried compiling an sdk once...

I'll merge the fixes for that from the multithreading-experimental branch into main as soon as that is stable, this time I'm even gonna test it! 

For now you should just use [this commit](https://github.com/Encryqed/Dumper-7/tree/3941d46872c35d28ef7a2aaf17b05df12f38ef5c).

**Comment by matty45** [comment]
Thanks

**Comment by Fischsalat** [comment]
Can you give the latest commit on [multithreading-experimental](https://github.com/Encryqed/Dumper-7/tree/multithreading-experimental) a try? Should work.

**Comment by matty45** [comment]
> Can you give the latest commit on [multithreading-experimental](https://github.com/Encryqed/Dumper-7/tree/multithreading-experimental) a try? Should work.

Ok

**Comment by matty45** [comment]
Tried it on that branch, code seems to be a little messed up still:

![weird code](https://i.imgur.com/btCiprK.png)

Line 25 in this code is a little weird

This generation bug happens on multiple generated header files.

I know there are errors due to duplicate files such as this:
Seat_1_functions.cpp
Seat_functions.cpp
but i would not call that a bug, just a minor frustration that you have to fix yourself as i dont think that can easily be fixed


There are also some type redefinitions such as this one in this generated stuct:
![weird code 2](https://i.imgur.com/8qFfsi7.png)

There are also some missing structs that do not get generated

**Comment by Fischsalat** [comment]
Did some of these errors also occur on older commits (working commit of main), or are all of them new?

**Comment by matty45** [comment]
brand new

**Comment by TimmieDevelops** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/79818585/0e77ba29-c285-4caf-bd46-cfa1c5653477)

ok now I start get errors on the class in the Fortnite dump

**Comment by TimmieDevelops** [comment]
And the files all Low case

**Comment by Puyodead1** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/14828766/afe23d96-0409-4d85-a750-50d858f452c4)
sad

**Comment by Fischsalat** [comment]
use the multithreading-experimental branch, it's fixed there

**Comment by TimmieDevelops** [comment]
alright thank you [Fischsalat](https://github.com/Fischsalat)
