### ISSUE TITLE
cant build project with sdk

### ISSUE THREAD

**Issue by NyanAlex** [Encryqed/Dumper-7#262]
Game: Bodycam
UE Version: 5.2

![image](https://github.com/user-attachments/assets/7822ab15-7d41-45e2-b950-1923cc9c64d7)

**Comment by Fischsalat** [comment]
I like that the affected lines aren't in the picture, making debugging it a lot easier.

**Comment by NyanAlex** [comment]
sorry
![image](https://github.com/user-attachments/assets/2fadff31-2b5e-40b9-af12-1a87c40d8730)
![image](https://github.com/user-attachments/assets/72b96b30-b83a-4d99-9daa-18561128c639)
![image](https://github.com/user-attachments/assets/59e2cb68-1fab-4873-993d-12b24d6b0c25)

**Comment by Fischsalat** [comment]
ah that shitty issue, just replace it with uint8

**Comment by NyanAlex** [comment]
![image](https://github.com/user-attachments/assets/3205b288-f5eb-4c5d-b464-bd3bf8b1ddd0)

**Comment by NyanAlex** [comment]
I replaced it with uint8 but now static_assert errors appeared

**Comment by Fischsalat** [comment]
Fix the variable redefinition. That shouldn't happen but somehow it did.

**Comment by NyanAlex** [comment]
![image](https://github.com/user-attachments/assets/8d64917b-7ba5-4076-a093-9551ead5ba2b)

**Comment by Fischsalat** [comment]
send the full dump

**Comment by Fischsalat** [comment]
compiles fine on my end
