### ISSUE TITLE
Basic.hpp problem

### ISSUE THREAD

**Issue by mr-kotik** [Encryqed/Dumper-7#265]
Game: Strinova
Im so newbie, learning
How can i fis this issues with SDK?
![devenv_KYI5XtqIlc](https://github.com/user-attachments/assets/6d45dada-8c61-434b-afb5-c137afbcdc79)

Souce code: https://drive.google.com/file/d/1s8Mf6gsilDvCQLG5QK5T1_ujbOOmhNzk/view?usp=sharing

**Comment by Fischsalat** [comment]
![image](https://github.com/user-attachments/assets/e6905a7e-7dcf-4510-9ea8-16910bb48e2a)
follow the guide, use c++latest
