### ISSUE TITLE
What is CppSDK folder as described in the process and where can I find it for my UE game?

### ISSUE THREAD

**Issue by davronverse** [Encryqed/Dumper-7#272]
Just as the title, what is CppSDK folder as described in the process and where can I find it for my UE game?

Cannot find it for my game nor have no idea what's that for.

**Comment by xVoidie** [comment]
CppSDK contains all the sdk files form the game, the default location is C:\\Dumper-7\\SomeGame, you get this when you inject Dumper 7 .dll into that games process

**Comment by davronverse** [comment]
Thanks!
