### ISSUE TITLE
"Fatal Error!" crash

### ISSUE THREAD

**Issue by Puyodead1** [Encryqed/Dumper-7#28]
I am trying to use this on a random pre-alpha game called Astro, it uses UE 5.2 and keeps giving me this error:
![image](https://github.com/Encryqed/Dumper-7/assets/14828766/1090052e-1b7f-4a2f-8137-94f23bd471c4)

I don't know if it matters or not but the game was distributed as a development build. 
I have tried using both an older commit (idk which, I built it a few weeks ago) and the most recent e6dde46579ff16f55e3585b31007687611bdc4cb

**Comment by TimmieDevelops** [comment]
oof

**Comment by Puyodead1** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/14828766/584251fa-ab3c-4c4c-8b6a-0abe256caee2)

**Comment by Puyodead1** [comment]
Ok, I guess it worked. there were 2 executable files, `Astro.exe` and `Astro-Win64-Shipping.exe`.  Trying to run `Astro-Win64-Shipping.exe`  gave some random ass error
``Serial size mismatch: Expected read size 214, Actual read size 198`` and would then crash, So I was just using Astro.exe, injecting dumper7 into the win64 shipping before it closes generated the sdk correctly `¯\_(ツ)_/¯`

**Comment by Fischsalat** [comment]
nice to see issues which resolve themselves
