### ISSUE TITLE
don't even know how to explain this

### ISSUE THREAD

**Issue by nexxnexx** [Encryqed/Dumper-7#33]
sdk on latest fn (ue 5.2, fn 25.11) generates both FortniteGame and FortniteAI files (structs, classes & params), and both of them are using structs from eachother, for example, `UAthenaAIBotDebugMiniMapIndicator : public UFortMiniMapIndicator` (from FortniteAI_classes) uses UFortMiniMapIndicator from FortniteGame_classes, so it leads to errors like `'SDK::UFortMiniMapIndicator': base class undefined` or `incomplete type is not allowed`, makes it impossible to compile

**Comment by Fischsalat** [comment]
Yea, I know about this. It's called cyclic-dependencies and it's damn hard to fix.

**Comment by nexxnexx** [comment]
i just fixed it by pasting the class/struct it needed and renaming it with an underscord
