### ISSUE TITLE
There are no instructions on how to use

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#34]
The project is missing instructions on how to actually use it. See UE's and Kn4cker's SDK Generator for adequate compilation and usage instructions examples:
https://github.com/EpicGames/UnrealEngine
https://github.com/polivilas/UnrealEngineSDKGenerator

**Comment by TimmieDevelops** [comment]
bro done fixing the issue no way

**Comment by Fischsalat** [comment]
Docs are on GNames-experimental until I merge it into main

**Comment by TimmieDevelops** [comment]
Nice
