### ISSUE TITLE
Crashes on a barebones UE4.13.2 project

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#35]
1. Ship a barebones UE4.13.2 project in x64 release configuration for Windows.
2. Compile Dumper-7 in x64 Release configuration.
3. Run the project.
4. Inject Dumper-7.dll into the barebones project.

Everything crashes.
Video:
https://github.com/Encryqed/Dumper-7/assets/16989713/654a3fb4-139c-49d9-8438-700db6e09e36

Also tried to inject it into a real game on 4.13.2 with the same result. Same result with a different injector.

**Comment by Fischsalat** [comment]
Older UE versions are not as well tested, it may be possible that a property I'm using to find some offset, doesn't exist on these versions. Could you upload the template game you made? This way I don't have to build it myself.

**Comment by KulaGGin** [comment]
Ok, here it is: https://drive.google.com/drive/folders/1sHYidhimYmlpUvqKVdYV6PJsnOU3XcDn?usp=sharing

**Comment by Fischsalat** [comment]
I have no idea why, but for some reason UEnum::Names has different types.

1. TArray<FName, int8> UEnum::Names:
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/77440b17-b055-409e-8492-fe85c336c296)

2. TArray<FName> UEnum::Names
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/fcf731f7-b445-472e-b3cb-a5c4b67ce346)

**Comment by TimmieDevelops** [comment]
What am i looking at here?

**Comment by Fischsalat** [comment]
Is there any game using 4.13 that crashes or is it just the template game? Because I'm going to close this issue if it's just the template.

**Comment by KulaGGin** [comment]
Tekken 7
