### ISSUE TITLE
The generator doesn't generate anything on 5.0.3 and 5.1.2 projects

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#36]
1. Ship a barebones UE5.0.3 project in x64 release configuration for Windows.
2. Compile Dumper-7 in x64 Release configuration.
3. Run the project.
4. Inject Dumper-7.dll into the barebones project.

Generator shows logs and reports done, but there are no folders and no files created.
Video:
https://github.com/Encryqed/Dumper-7/assets/16989713/a44a9cdb-f4d0-42ad-9cde-6904c5d4558f

Log:
```
Started Generation [Dumper-7]!

Dumper-7 by me, you & him


Searching for GObjects...

Found FChunkedFixedUObjectArray GObjects at offset 0x7bc7c70

Found FName::AppendString at Offset 0x1a3e200

Off::UStruct::Children: 48
Off::UField::Next: 28
Off::UStruct::SuperStruct: 40
Off::UStruct::Size: 58
Off::UClass::CastFlags: d8
Game uses FProperty system

Off::UStruct::ChildProperties: 50
Off::UClass::ClassDefaultObject: 110
Off::UEnum::Names: 40
Off::UFunction::FunctionFlags: b0

Off::UProperty::ElementSize: 3c
Off::UProperty::ArrayDim: 38
Off::UProperty::Offset_Internal: 4c
Off::UProperty::PropertyFlags: 40
UPropertySize: 78

Off::UArrayProperty::Inner: 78
Off::USetProperty::ElementProp: 78
Off::UMapProperty::Base: 78

PE-Offset: 0x1ca07b0
PE-Index: 0x4b

GameName: UE53rdPersonShooter
GameVersion: 5.0.3-20979098+++UE5+Release-5.0



[=] Done [=]
```

Also tried to inject it into a real game on 5.1.2 with the same result. Same result with a different injector.

I do have write access to all of these folders and other generators like UE4SS do successfully generate headers for UHT.

**Comment by Fischsalat** [comment]
All SDKs are generated into the path specified in Settings.h, this path is, by default, `C:\Dumper-7`. The SDK will be in a folder named `{EngineVersion}-{GameName}`.

**Comment by KulaGGin** [comment]
I see. Ok. Well, it isn't anywhere on the repo and it is a random path to look for. Adding basic documentation would be helpful to people.

**Comment by Fischsalat** [comment]
I just did.
