### ISSUE TITLE
Error On Unreal 4.26.1

### ISSUE THREAD

**Issue by TimmieDevelops** [Encryqed/Dumper-7#39]
idk if you already fixed this, but it gave me an error. However, I have already fixed it. :/
![image](https://github.com/Encryqed/Dumper-7/assets/79818585/c36798e3-0335-4666-9e32-96e2de7b8e71)

**Comment by Fischsalat** [comment]
Currently I'm checking just for TRUE on main, and for TRUE/FALSE on GNames-experimental. 

I will not add more checks for names colliding with enum-names. There are just too many unscoped enums in Windows.h and other legacy C-Headers.
