### ISSUE TITLE
How do I use the SDK?

### ISSUE THREAD

**Issue by gamerbross** [Encryqed/Dumper-7#43]
Sorry for the dumb question.
But there is any tutorial about making a DLL or something with the SDK? Like how to correctly add it into the project.
I tried but I have a lot of errors.
![image](https://github.com/Encryqed/Dumper-7/assets/55158797/93e93dcb-1c9a-42be-bf85-bf608d5c4187)
This is the only one that I couldn't fix.

**Comment by gamerbross** [comment]
My bad, i was removing inline from the offsets because they gave me an error because i wasnt using the latest c++ version

**Comment by SupJko** [comment]
skill issue

**Comment by TimmieDevelops** [comment]
lol
