### ISSUE TITLE
No overloaded function requires 2 arguments build error

### ISSUE THREAD

**Issue by ALittlePatate** [Encryqed/Dumper-7#45]
Dumper-7\Dumper\Generator.cpp(1531,13): error C2661: 'FileWriter::Write': no overloaded function requires 2 arguments.

Seems like you forgot to update something

**Comment by Fischsalat** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/66f3692d-c37f-4b49-875f-35536d1bc4b4)
put the closing brace on the wrong line, lol. Could've sworn I tried compiling it.

**Comment by GoatHEN** [comment]
Hey, sorry for messaging in a closed issue.

Im having the same issue and cant figure out whats wrong exactly even with your comment.
Any way you could explain a bit more or push an update to resolve this?

Thanks

**Comment by Fischsalat** [comment]
I closed the issue because I fixed it. And I forgot to commit and push the change to the repo...
