### ISSUE TITLE
(ARK: SE) Crashing at Kismet.ProcessEvent(GetGameName, &Name);

### ISSUE THREAD

**Issue by Barthalamul3** [Encryqed/Dumper-7#51]
Hopefully the title and picture is enough information. I'm still new to this and would appreciate any constructive criticisms. Thanks!
![D-7Crash](https://github.com/Encryqed/Dumper-7/assets/81845070/851e9aae-1ea7-4e26-a9c8-125d2de92020)

**Comment by Barthalamul3** [comment]
Update: commenting out Kismet.ProcessEvent(GetGameName, &Name) and Kismet.ProcessEvent(GetEngineVersion, &Version) solved the issue.

**Comment by Fischsalat** [comment]
That PE index seems wrong, manually setting version/name fixed it because PE isn't getting called if those are set already.

Make sure to replace the index in SDK.hpp with the correct index.
