### ISSUE TITLE
Can't get static classes

### ISSUE THREAD

**Issue by desumachii** [Encryqed/Dumper-7#52]
i was trying to get the static class in my internal but it gives me no result

```cpp
/*Objects & Names inits*/

auto GStatic = (SDK::UGameplayStatics*)SDK::UGameplayStatics::StaticClass();/// 0000000000
```

but when i try to get those static classes on the dumper it gives me results 
```cpp
UEClass GStatic = ObjectArray::FindClassFast("GameplayStatics"); /// 000000002D064E40
```

**Comment by Fischsalat** [comment]
Strange. Can you send me the sdk?

**Comment by desumachii** [comment]
here's the sdk
https://www.mediafire.com/file/ltebn2uuanaq2dm/4.25.4-0+++UE4+Release-4.25-NEXT-ArkGame.rar/file

**Comment by Fischsalat** [comment]
bruh, you didn't even send the sdk.

**Comment by desumachii** [comment]
sorry for that, there's the new one https://www.mediafire.com/file/2ncu6r97yzl8sy6/SDK.zip/file

**Comment by Fischsalat** [comment]
Instead of the first example from above you're supposed to use `::GetDefault()` instad. Also, does finding other objects work? Can you iterate over GObjects, does UObject::GObjects->GetByIndex(30) return a valid pointer?

**Comment by desumachii** [comment]
> Instead of the first example from above you're supposed to use `::GetDefault()` instad. Also, does finding other objects work? Can you iterate over GObjects, does UObject::GObjects->GetByIndex(30) return a valid pointer?
no it doesn't return a valid pointer

**Comment by desumachii** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/45435949/cdda23ed-525f-464e-967c-af91c1e3b532)

**Comment by desumachii** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/45435949/cac32775-3574-4597-942f-8b81300da0f5)
in my log the pointer was 0x2cb45dc0 but on the dump it was 0x2cb35dc0

**Comment by Fischsalat** [comment]
Heap memory is dynamic, addresses change when restarting. So does everything work? you also need to show me what you're printing, not just the result.

**Comment by desumachii** [comment]
> UObject::GObjects->GetByIndex(30)

getting static class works now. 

for some reason when im using the "GetAllActorsOfClass"
it crash at Class->GetFunction("GameplayStatics", "GetAllActorsOfClass");

![image](https://github.com/Encryqed/Dumper-7/assets/45435949/35328a82-0823-4ec0-81c9-95c6ee5a6696)

//init
GPStatics = (SDK::UGameplayStatics*)SDK::UGameplayStatics::StaticClass()->GetDefaultObj(); //get StaticClass defaultObj


//caching
SDK::TArray<SDK::AActor*> actors;
GPStatics->GetAllActorsOfClass(World, (SDK::AActor*)SDK::AArkPlayer::StaticClass(), &actors);

**Comment by Fischsalat** [comment]
what kind of pseudocode is that? send the actual code you're using

**Comment by desumachii** [comment]
> what kind of pseudocode is that? send the actual code you're using

it just a bunch of printf. i can't actually debug cuz the AC is active

```cpp

void UGameplayStatics::GetAllActorsOfClass(class UObject* WorldContextObject, class AActor* ActorClass, TArray<class AActor*>* OutActors)
{
	printf("GetAllActorsOfClass Starting\n");
	static class UFunction* Func = nullptr;

	if (!Func)
		Func = Class->GetFunction("GameplayStatics", "GetAllActorsOfClass");

	Params::UGameplayStatics_GetAllActorsOfClass_Params Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ActorClass = ActorClass;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;
	printf("GetAllActorsOfClass ProcessEvent start\n");
	UObject::ProcessEvent(Func, &Parms);
	printf("GetAllActorsOfClass ProcessEvent end\n");


	Func->FunctionFlags = Flgs;

	if (OutActors != nullptr)
		*OutActors = std::move(Parms.OutActors);
	printf("GetAllActorofClass Ending\n");
}
```
```cpp
class UFunction* UClass::GetFunction(const std::string& ClassName, const std::string& FuncName)
	{
		printf("GetFunction [%s][%s]\n", ClassName.c_str(), FuncName.c_str());
		for(UStruct* Clss = this; Clss; Clss = Clss->Super)
		{
			printf("for(UStruct* Clss = this; Clss; Clss = Clss->Super) [%llx] [%s]\n", (void*)Clss, Clss->GetName().c_str());
			if (Clss->GetName() == ClassName)
			{
				printf("if (Clss->GetName() == ClassName) [%s]\n", Clss->GetName().c_str());
				for (UField* Field = Clss->Children; Field; Field = Field->Next)
				{
					printf("for (UField* Field = Clss->Children; Field; Field = Field->Next) [%llx]\n", (void*)Field);
					if(Field->HasTypeFlag(EClassCastFlags::Function) && Field->GetName() == FuncName)
					{
						printf("if(Field->HasTypeFlag(EClassCastFlags::Function) && Field->GetName() == FuncName) [%s]\n", Field->GetName().c_str());
						return static_cast<class UFunction*>(Field);
					}	
				}
			}
		}
		return nullptr;
	}
	```

**Comment by Fischsalat** [comment]
`SDK::UGameplayStatics::StaticClass()->GetDefaultObj()` -> `SDK::UGameplayStatics::GetDefaultObj();`

you're somehow mananging to call "GetAllActorsOfClass" on an instance of a UClass, call it on an actual GameplayStatics object

**Comment by desumachii** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/45435949/2fffa454-ed11-4044-93bc-d912b85ee26f)
it works!! thanks alot

**Comment by Fischsalat** [comment]
:|
