### ISSUE TITLE
Wrong offsets on DBD

### ISSUE THREAD

**Issue by Umbra999** [Encryqed/Dumper-7#55]
Hello i just tried generating an SDK for Dead by Daylight, i get a lot of errors in the static_assert that offsets are wrong? Is there a way to fix it inside my cheat or do i need to use manual overrides in the Generator.cpp? 

![Screenshot 2023-10-24 170508](https://github.com/Encryqed/Dumper-7/assets/69671761/eb542d77-e1c6-47f7-a960-57ae188521e4)

**Comment by Fischsalat** [comment]
I'm looking for a fix to those issues, for now just fix the padding manually. This issue is only affecting the classes within the static_assert's and their child classes. Other than  those classes the sdk should have generated just fine.

**Comment by Fischsalat** [comment]
Could you please send me the **UNFIXED** SDK? Thanks.

**Comment by Umbra999** [comment]
Sure here it is
[4.27.2-1387481+++DeadByDaylight+Live-DeadByDaylight.zip](https://github.com/Encryqed/Dumper-7/files/13167362/4.27.2-1387481%2B%2B%2BDeadByDaylight%2BLive-DeadByDaylight.zip)
