### ISSUE TITLE
Crash when getting class

### ISSUE THREAD

**Issue by TheGeogeo** [Encryqed/Dumper-7#56]
Hi,

When i want get UGameplayStatics or any class in engine the game crash.

```c++
static inline SDK::UGameplayStatics* GPStatics = nullptr;
//---
if (!this->GPStatics) this->GPStatics = (SDK::UGameplayStatics*)SDK::UGameplayStatics::StaticClass();
```
I change like in this issue : https://github.com/Encryqed/Dumper-7/issues/52

```c++
static inline SDK::UGameplayStatics* GPStatics = nullptr;
//---
if (!this->GPStatics) this->GPStatics = (SDK::UGameplayStatics*)SDK::UGameplayStatics::GetDefaultObj();
```
And it crash too.

Thx for any reply.

**Comment by Fischsalat** [comment]
Check if the offsets in UObject, UStruct, UFunction and UClass are correct. Did any of the assertions at the bottom of SDK.hpp fail? If one of the offsets is wrong you need to fix it by hand for now. 

I'm going to make sure offsets of predefined members wont be an issue in the rewrite!

**Comment by TheGeogeo** [comment]
Ok thx, i fix it later.
