### ISSUE TITLE
SoT cannot be dumped

### ISSUE THREAD

**Issue by TheGeogeo** [Encryqed/Dumper-7#57]
Hey,
SoT cannot be dumped. They modify the Engine ?

![image](https://github.com/Encryqed/Dumper-7/assets/57634077/8e5ca2c4-b28e-4ef9-b9c2-5efd3ff81d4b)

**Comment by Fischsalat** [comment]
try overriding the offset...

**Comment by TheGeogeo** [comment]
I add sig here and it find adress:
![image](https://github.com/Encryqed/Dumper-7/assets/57634077/fe20d82b-7f10-49b4-8e61-11f557aae3fc)

But when it dump it crash during that:
![image](https://github.com/Encryqed/Dumper-7/assets/57634077/342519f8-8d9f-4080-a732-c059b0b7098f)

**Comment by TheGeogeo** [comment]
Weird it get all adress but crashing all time i don't know how to fixing it

**Comment by Fischsalat** [comment]
try debugging it

**Comment by Fischsalat** [comment]
What do you mean by the first point? GObjects/GNames change very rarely. GObjects only two or three times accross all of UE4-5 and GNames only once or twice.

**Comment by RoeanAigis** [comment]
this shouldn't have been closed as completed because the issue still remains
