### ISSUE TITLE
Alignment and struct size bug

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#58]
Check out these structs:
```
// 0x40 (0x2D8 - 0x298)
// Class Polaris.Barrier
class ABarrier : public AActor
{
public:
	TArray<struct FWallBarrierGroup>             WallBarrierGroups;                                 // 0x298(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FBarrierGroup>                 BarrierGroups;                                     // 0x2A8(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FWallBarrierGroup>             WallCullBackGroups;                                // 0x2B8(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FBarrierInitializeRequestOne>  InitializeRequest;                                 // 0x2C8(0x10)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)

	static class UClass* StaticClass();
	static class ABarrier* GetDefaultObj();

	struct FBarrierInitializeRequestOne PopInitializeRequest();
};

// 0xD9 (0x3B1 - 0x2D8)
// BlueprintGeneratedClass BP_Barrier.BP_Barrier_C
class ABP_Barrier_C : public ABarrier
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x2D8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                       DefaultSceneRoot;                                  // 0x2E0(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                       MinDistance;                                       // 0x2E8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       MaxDistance;                                       // 0x2F0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       MinHeight;                                         // 0x2F8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       MaxHeight;                                         // 0x300(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       FloorHeightFB;                                     // 0x308(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       FloorBarrierAlphaOffset;                           // 0x310(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>      MIDs;                                              // 0x318(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class ABP_WallBarrierCamera_C*>       OverlapVolumes_DEPLICATED;                         // 0x328(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate)
	double                                       OverlapVolumeCount_DEPLICATED;                     // 0x338(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       PrevOverlapVolumeCount_DEPLICATED;                 // 0x340(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         UseOverlapVolumes_DEPLICATED;                      // 0x348(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_1C7A[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<class UMaterialInstanceDynamic*>      EffectMIDs;                                        // 0x350(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                       FloorHeight;                                       // 0x360(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         EnabledCullBack;                                   // 0x368(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         QueuedVisibility;                                  // 0x369(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Queueing;                                          // 0x36A(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Initialized;                                       // 0x36B(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_1C7B[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       DistanceScale;                                     // 0x370(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       AlphaOffset;                                       // 0x378(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                               FacadeVector;                                      // 0x380(0x18)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         LocalFacade;                                       // 0x398(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_1C7C[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       AlphaOffset1;                                      // 0x3A0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        Step;                                              // 0x3A8(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        NumReplaceTimeSlice;                               // 0x3AC(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         EveryBattle_StageReset;                            // 0x3B0(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// 0xF (0x3C0 - 0x3B1)
// BlueprintGeneratedClass BP_BarrierCol1.BP_BarrierCol1_C
class ABP_BarrierCol1_C : public ABP_Barrier_C
{
public:
	uint8                                        Pad_1035[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UBoxComponent*                         Box;                                               // 0x3B8(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class ABP_BarrierCol1_C* GetDefaultObj();

};
```

I'm interested in the `ABP_BarrierCol1_C::Box` member. It's commented  by the dumper offset of 0x3B8 is correct: I verified it manually with reclass.

But the tests won't pass here:
```
static_assert(offsetof(ABP_BarrierCol1_C, Box) == 0x3B8);
static_assert(sizeof ABP_BarrierCol1_C == 0x3C0);
```

The reason they won't pass is because size of `ABP_Barrier_C` is actually 0x3B8, because it has its' last member at offset 0x3B0: `bool EveryBattle_StageReset`, and so it's size becomes 0x3B1, but then the compiler aligns struct's size to be 0x3B8. But then at the start of `ABP_BarrierCol1_C` it also adds 7 bytes of padding, and the offset of the `Box` becomes 0x3C0 and the size of `ABP_BarrierCol1_C` becomes 0x3C8.

The SDK dumper reports the size of `ABP_Barrier_C` to be 0x3B1. I also verified it manually and it does report 0x3B1 in the reflection system. But I doubt it is, since the default on x64 is to align structs bigger than 8 by 16, align pointers by 8, etc.

I don't think this bug was present in the original Kn4cker's SDK generator. So whatever algorithm he wrote to add paddings should also work here correctly.

**Comment by Fischsalat** [comment]
The bug **is** present in other dumpers, but in a different form. 

So, the size of `ABP_Barrier_C`, according to UEs reflection system, is `0x3B8`, as it is 8byte aligned. But sometimes following members of child classes are placed **within** the trailing padding of a struct. In this case there exists a child class, somewhere, with a member at offset `0x3B1` (any 1 byte aligned type).

![image](https://github.com/Encryqed/Dumper-7/assets/64608145/1335e511-e4a8-4516-8057-8966039c5254)

Other generators ignore this issue completely and pad the struct until it reaches the size given by the reflection system (the size that already contains trailing padding). On those other generators the members of child classes have a wrong offset following that issue. 

On my generator I search for the smallest offset of a member of a child class, so I find members placed in trailing padding, and avoid explicitly padding out that size with a `uint8[]`. But, classes such as `ABP_BarrierCol1_C ` then add padding before the member to make up for the difference from `sizeof(SuperClass)` to `offsetof(ChildMember)`. These classses ignore the implicitely added n bytes of padding, 7 in this case, and add them themselves.

To avoid this kind of issue I could check for `sizeof(SuperStruct)` and `alignof(ChildMember)` and assume for the compiler to do the work of padding.

**Comment by KulaGGin** [comment]
> The bug **is** present in other dumpers, but in a different form.
> 
> So, the size of `ABP_Barrier_C`, according to UEs reflection system, is `0x3B8`, as it is 8byte aligned.

No, no. You see, when I check the size of the struct in UEs reflection system manually with Reclass and do BP_BarrierCol1_South->Class->Size on the object of this class, it does in fact report 0x3B1 in the reflection system, and you can see the SDK reported the same from this field: `// 0xD9 (0x3B1 - 0x2D8)`. Which is a reflection system bug most probably, because the real compiled size is 0x3B8. I didn't check the constructor and how much memory is allocated but I bet it's 0x3B8 actually in C++.

> But sometimes following members of child classes are placed **within** the trailing padding of a struct. In this case there exists a child class, somewhere, with a member at offset `0x3B1` (any 1 byte aligned type).

There is no class with a member at 0x3B1 anywhere: not in C++ and not in the reflection system:
![devenv_UylZSJUFjJ](https://github.com/Encryqed/Dumper-7/assets/16989713/207885de-2155-4107-afce-f1e939345a24)

There's only 1 class that inherits from `ABP_Barrier_C` and its' first member is at 0x3B8: `UBoxComponent* Box`

> On my generator I search for the smallest offset of a member of a child class, so I find members placed in trailing padding, and avoid explicitly padding out that size with a uint8[].

> But, classes such as ABP_BarrierCol1_C  then add padding before the member to make up for the difference from sizeof(SuperClass) to offsetof(ChildMember). These classses ignore the implicitely added n bytes of padding, 7 in this case, and add them themselves.

I don't think this is what's happening. I think the bug is because you assume that char array is 1-byte aligned.
You do logically add the padding before the first member of the inheriting class `ABP_BarrierCol1_C`. The thing is that arrays on x64 are 4-byte aligned. `uint8 Pad_1035` is put on the next 4-byte alignment, which is 0x3B4 in our case. Then it goes from 0x3B4 to 0x3BB. Then the `UBoxComponent* Box` gets compiled at 0x3C0. That's the problem. So the `ABP_BarrierCol1_C` doesn't ignore anything, it just puts the padding at 4-byte aligned offset after the previous member as per compiler's rules.
Here's a program that demonstrates this problem with arrays being 4-byte aligned: https://godbolt.org/z/K4T3GGEcs

> To avoid this kind of issue I could check for `sizeof(SuperStruct)` and `alignof(ChildMember)` and assume for the compiler to do the work of padding.

Yes. And also assume that the arrays are 4-byte aligned and not 1-byte aligned when you add the padding. This should become pretty without unnecessary paddings and also fix the bug. Here are the rules for alignment in case of there are some other bugs: https://learn.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170

Also, I don't mind fixing it myself and creating a pull request. I haven't looked into the code of the generator, so not sure how quickly I'd find a place to fix this bug at.

**Comment by Fischsalat** [comment]
> No. bool c doesn't get placed inside of Example1's padding. Here's the example with running tests on latest x64 msvc that  demonstrates it:
I know, this was an example. I'm still not sure under which circumstances the compiler decides to use the trailing padding of a class for additional padding.

> There is no class with a member at 0x3B1 anywhere: not in C++ and not in the reflection system:
Well, I guess this **is** a bug then.

> But the thing is that the real size of ABP_Barrier_C isn't 0x3B1 as the reflection system reports, it's 0x3B4,
No, The struct is 8-byte aligned, the real size, including trailing padding, is `0x3B8`

> Here's a program that demonstrates this problem: https://godbolt.org/z/K4T3GGEcs
I'm aware of the problem, the padding wont be placed in the trailing padding of the struct that comes before. The example program doesn't compile btw.

> And also assume that the total struct sizes are 4-byte aligned and not 1-byte aligned when you add the padding.
This only matters in the cases of padding before the first member, or after the last member. Also assuming 4 byte alignment isn't very good either. It's 8-byte in most cases (due to most classes containing pointers, TArrays, etc.), but I can use `UStruct::MinAlignment` instead of assuming one alignment for every class/struct.

> Here are the rules for alignment in case of there are some other bugs: https://learn.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170
This document only really describes the rules of `alignas` and some other basic knowledge about struct alignment, this sadly doesn't really help with the issue of tailing padding.

**Comment by Fischsalat** [comment]
You can send me messages on discord for a more efficient discussion of this bug.

Discord: `fischsalat`

**Comment by Fischsalat** [comment]
# Description of bugs and fixes surrounding this ticket

### Note: 
The terms _struct_/_class_ are used interchangeably, except when explicitly differentiated. 

## Bug 1 (Unreal Engine reflection system):
### Description:
A class is bigger than the offset of the first member of a child class. This causes wrong offsets in the child class and its children.
### Occurrence: 
Fortnite Patch 1.7.2 (UE4.16), most UE games, including newer engine-versions
### Example:
```c++
sizeof(UEngine) = 0xC90;

// In UGameEngine, a direct child class of UEngine:
offsetof(MaxDeltaTime) = 0xC88;
offsetof(ServerFlushLogInterval) = 0xC8C;
offsetof(GameInstance) = 0xC90;
```
### Fix:
Iterating over all classes, finding a classes' lowest offset and setting the Size of the super-class to this lowest offset, if it is below the super-classes' original size. 
This is currently still implemented with a map: 
```c++
std::unordered_map<int32 /* StructIndex */, int32 /* Size */> StructSizes;
```

## Bug 2 (Unreal Engine reflection system):
### Description:
The variable `UStruct::MinAlignment` isn't properly initialized for `UClasses`, this issue only affects classes, **not** structs. The `MinAlignment` is initialized to 0x1, ignoring the real alignment of the class. The real alignment is at least 0x8 bytes, as all classes described by `UClass`, inherited from `UObject`, which contains pointers and therefore has pointer alignment. Greater alignment coming from members of types with a greater alignment, such as `FTransform` with `alignof(FTransform) == 0x10`, is also ignored, yielding wrong class alignment and possibly also wrong size.
### Occurrence: 
Fortnite Patch 1.7.2 (UE4.16)
### Example:
```c++
// From print statement printing UStruct::MinAlignment for different classes:
alignof(UObject) = 0x1;
alignof(UEngine) = 0x1;

alignof(FTransform) = 0x10;
alignof(FVector) = 0x4;
```
### Fix:
Iterating over all classes, checking each member variable for alignment, greater than `UStruct::MinAlignment`. The highest alignment found is then taken and set to be the classes' alignment. Because alignment is also inherited, the program iterates over all classes again, setting the alignment of a child-class to the super-classes' alignment, if it is greater.

## Bug 3 (Dumper-7):
### Description:
The generator doesn't account for trailing padding properly and generates unnecessary padding inside of a child class. This over-the-top padding then breaks the size of the child class.
### Occurrence: 
Nearly every game
### Example:
```c++
struct Example1
{
        void* Vft; // 0x0 - 0x8
        bool bIsTrue; // 0x8 - 0x9
        // Implicit 0x7 bytes of padding
};

struct Example2 : public Example1
{
        uint8 Pad[0x7]; // duplication of implicit padding
        double Value; // 0x10 - 0x18
};
```
Instead of replacing the trailing padding of `Example1`, the padding at the start of `Example2` shifts the position of the variable `Value` to the incorrect offset of 0x18.
### Fix:
Account for a classes' trailing padding when calculating the size of the class, by rounding up the size to the nearest multiple of the alignment.
```c++
template<typename T>
constexpr T Align(T Size, T Alignment)
{
	return Size + (Alignment - (Size % Alignment));
}
```

**Comment by Fischsalat** [comment]
This issue has been resolved and all structs/classes should have the right size, and all members the correct offset now.

Currently there's still `static_assert`s being generated with every SDK on the new main branch (formerly GeneratorRewrite) which are not failing on any of the tested games. The assertions will be turned off in the future, when even more games have been verified to work.
