### ISSUE TITLE
GetRawString Crashing

### ISSUE THREAD

**Issue by Umbra999** [Encryqed/Dumper-7#59]
Using GetRawString crashes on some Names, i'm not sure yet why i can get some names and some don't but it appears to be an issue with AppendString, is there an alternative to use maybe? Im using it on Dead by Daylight which is EAC protected if thats related

**Comment by Fischsalat** [comment]
Try running without EAC. If it still doesn't work debug (if possible) to see if the object, of whom it is trying to get the name, is valid.
You can also try setting `AppendString = nullptr;` right before the check for it to be nullptr inside of `FName::Init()`, this forces it to use `GNames` instead.

**Comment by Umbra999** [comment]
i can not really test it without eac because the game kick me out before the stuff where i use it, when set AppendString to a nullptr it is stuck on "Searching for GNames...", after that nothing happens not even the error that GNames couldn't be found

**Comment by Fischsalat** [comment]
Huh, weird.

**Comment by Umbra999** [comment]
I manually imported a GNames logic now and the crashes stopped and everything working completly fine so i assume its some issue that appears only on AppendString? Here is the code that i use if it helps in any way:

I call FName::InitGNames() when the cheat initializes.

```
struct FNameEntryHandle {
	uint32_t Block = 0;
	uint32_t Offset = 0;

	FNameEntryHandle(uint32_t block, uint32_t offset) : Block(block), Offset(offset) {};
	FNameEntryHandle(uint32_t id) : Block(id >> 16), Offset(id & 65535) {};
	operator uint32_t() const { return (Block << 16 | Offset); }
};

struct FNameEntry {
	uint32_t comparison_id;
	uint16_t bIsWide : 1;
	uint16_t Len : 15;
	union
	{
		char AnsiName[1024];
		wchar_t	WideName[1024];
	};

	std::string String();
};

struct FNamePool
{
	BYTE Lock[8];
	uint32_t CurrentBlock;
	uint32_t CurrentByteCursor;
	BYTE* Blocks[8192];

	FNameEntry* GetEntry(FNameEntryHandle handle) const;
};
```

```static inline FNamePool* GNames = nullptr;```
```
static inline void InitGNames()
{
	static byte poolSig[] = { 0x4C, 0x8D, 0x0D, 0x00, 0x00, 0x00, 0x00, 0xEB, 0x1E, 0x48, 0x8D, 0x0D };
	GNames = reinterpret_cast<decltype(GNames)>(Utils::FindPointer(GetModuleHandleA(nullptr), poolSig, sizeof(poolSig), 0));
}
```

```
inline std::string GetRawString() const
{
	if (!GetDisplayIndex()) return "none";

	SDK::FNameEntry* entry = GNames->GetEntry(GetDisplayIndex());
	if (!entry) return "none";

	std::string name = entry->String();

	return name;
}
```

**Comment by Fischsalat** [comment]
Accidentally injected Dumper-7 into a game protected by EAC and it got stuck after finding GObjects. I try finding out what causes this, but instead I'll just advise you not to do something like this.

You can start almost any game without anticheat, just find a way and inject the dumper then.

**Comment by Umbra999** [comment]
Yes i already dump without EAC enabled but the issue with being stuck in GNames appears on the unprotected process. The issue related to GObjects i didn't faced yet

**Comment by Fischsalat** [comment]
Does AppendString also crash without eac?

**Comment by Umbra999** [comment]
I can't really test it, the problem is that AppendString seems to work until something weird happens, i have a ProcessEvent hook to just dump the names, so far so good it works until it random crashes at some point, the issue is gone since i use GNames tho. Without EAC i don't get to the point where it would crash for usual so i have no clue if thats an EAC related issue or not. I already made a ton of nullchecks but nothing is null. My second try was removing AppendString and replace it with a default string which didnt crashed my game then so i know it is the AppendString but i just don't get why it is like that

**Comment by Fischsalat** [comment]
Wait, are you talking about the dumper or an injected dll?

**Comment by Umbra999** [comment]
for AppendString i mean the injected dll, for the issue where its stuck a Finding GNames i mean the dumper

**Comment by Fischsalat** [comment]
Can you send your code that is crashing with AppendString?

**Comment by Umbra999** [comment]
```
for (auto i = 0; i < LevelActors.Num(); i++)
{
	if (!LevelActors.IsValidIndex(i)) continue;

	SDK::AActor* Actor = LevelActors[i];
	if (!Actor || !Actor->IsA(SDK::ADisplayStand::StaticClass())) continue; <-- crashing at IsA
}
```

**Comment by Umbra999** [comment]
I finally got some time to recheck the issue and it looks like the array is just fine, for testing purpose i also removed it and did something like 

```
bool EventHandler::PrefixEvent(SDK::UClass* Instance, SDK::UFunction* Function, void* Params)
{
	if (Instance->IsA(SDK::UPlayerInteractionHandler::StaticClass())) { }
}
```

And it crashed too. with GNames i dont have this issue and the array and also this processEvent hook just works fine.

**Comment by Fischsalat** [comment]
So StaticClass and other functions using FindObject are crashing?m

**Comment by Umbra999** [comment]
> So StaticClass and other functions using FindObject are crashing?

yes

**Comment by Fischsalat** [comment]
Can you dump GObjects without crashing? (In the sdk)

**Comment by Umbra999** [comment]
nope its also crashing but when i start using any GetName function or the raw string directly

**Comment by Fischsalat** [comment]
Is it crashing after n times, or on certain names?

**Comment by Umbra999** [comment]
seems to crash on certain names

**Comment by Fischsalat** [comment]
Like which names?

**Comment by Umbra999** [comment]
if i would just know that... i cant get the string or classname obviously to see it and i have no idea on how to get a identifier without the name. I tried debugging it without eac but its fine in the main menu after the main menu eac is required but with eac i also come that far, it dies somewhere in the selection menu which needs eac to be running so no way to test it without eac there

**Comment by Umbra999** [comment]
on DBD it seems to be an issue with the anticheat to use AppendString, i saw another issue that got created which mentions that GNames will be stuck on DBD generation too (without anticheat) so i tested it myself and its indeed freezing after "Searching for GNames" inside the InitializeNamePool. The GNames offset is correct so this can not be the issue. Right now i handle it manually by adding a custom GNames implementation to the Basic classes inside my SDK after every dumb which can get kind of annoying. Is there any idea why this could happen or is that a known problem on UE Version 4.27.2?

**Comment by Fischsalat** [comment]
There isn't really a known problem, did you test the GeneratorRewrite branch yet? It's nearly fully done and the sdk should work fine if generated. If there's any issues with generation on that branch let me know!

**Comment by Fischsalat** [comment]
Any news on this?

**Comment by Umbra999** [comment]
just tested, appenstring still crashing it due the AC and GNames crashing the dumper. So same issue like before, offset is correct very weird

**Comment by Fischsalat** [comment]
So it's crashing because of an anticheat?

**Comment by Umbra999** [comment]
On AppendString it seems like its an anticheat problem yes, why its crashing/being stuck on GNames i have no idea. I always dump without anticheat off so that cant be the issue. very weird

**Comment by Fischsalat** [comment]
You did try the latest Main branch (now GeneratorRewrite) and it had the problem with GNames, right?

**Comment by Umbra999** [comment]
yes exactly, on GeneratorRewrite its just crashing on the GNames, before on the main branch it was just stuck forever, i assume the issue is somewhere in the InitializeNameArray / InitializeNamePool

**Comment by Fischsalat** [comment]
It probably didn't find GNames, I'll improve on that soon.

**Comment by Umbra999** [comment]
Thats the crash i get on the newest dumper version 
![Bild_2024-02-26_103315718](https://github.com/Encryqed/Dumper-7/assets/69671761/89447aa6-9e67-40a7-87cc-0b2899ee99a1)

**Comment by Umbra999** [comment]
I attached the debugger and it seems to die here:
![image](https://github.com/Encryqed/Dumper-7/assets/69671761/2a7e1ec6-4655-48f1-8ab5-5e3d4c7595ce)
![image](https://github.com/Encryqed/Dumper-7/assets/69671761/833afccb-52d6-458f-b4c2-29aa86769ac5)

And here is a GObjects dump:
[GObjects-Dump.txt](https://github.com/Encryqed/Dumper-7/files/14426624/GObjects-Dump.txt)

**Comment by Fischsalat** [comment]
yea, my discord is the same

**Comment by Umbra999** [comment]
> yea, my discord is the same

alright added you, my discord is "notumbra"

**Comment by Fischsalat** [comment]
I did not receive a friendrequest.

**Comment by Umbra999** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/69671761/ee4b46de-dca0-49c5-b78b-c39571c41727)
HUH
