### ISSUE TITLE
how can i watch UDataTable details data

### ISSUE THREAD

**Issue by yuanfeng-net** [Encryqed/Dumper-7#60]
class UDataTable : public UObject
{
public:
	class UScriptStruct*                         RowStruct;                                         // 0x28(0x8)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                        Pad_2199[0x50];                                    // Fixing Size After Last Property  [ Dumper-7 ]
	uint8                                        bStripFromClientBuilds : 1;                        // Mask: 0x1, PropSize: 0x10x80(0x1)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                        bIgnoreExtraFields : 1;                            // Mask: 0x2, PropSize: 0x10x80(0x1)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                        bIgnoreMissingFields : 1;                          // Mask: 0x4, PropSize: 0x10x80(0x1)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                        BitPad_103 : 5;                                    // Fixing Bit-Field Size  [ Dumper-7 ]
	uint8                                        Pad_21B8[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FString                                ImportKeyField;                                    // 0x88(0x10)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                         InInitialLoadOrDestruction;                        // 0x98(0x1)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                        Pad_21B9[0x1F];                                    // Fixing Size Of Struct [ Dumper-7 ]

	static class UClass* StaticClass();
	static class UDataTable* GetDefaultObj();

};

**Comment by Fischsalat** [comment]
Add it and read from it then. https://github.com/EpicGames/UnrealEngine/blob/5.3/Engine/Source/Runtime/Engine/Classes/Engine/DataTable.h#L69

**Comment by yuanfeng-net** [comment]
OK,thank
