### ISSUE TITLE
How can I find all UUserWidgets?

### ISSUE THREAD

**Issue by wojiaoz71** [Encryqed/Dumper-7#62]
As a beginner, this is a great tool. How can I use SDK files to find all UUserWidgets in the game?

**Comment by Fischsalat** [comment]
Iterate over all objects and check if the object is a `UUserWidget`.

And please stop abusing GitHub Issues as question boards. Issues should only be used for, well, issues and maybe feedback or suggestions. But not for questions about how to do something that isn't related to this SDK generator or its' specific SDK.
