### ISSUE TITLE
TSoftObjectPtr, TSoftClassPtr,etc.. is not a class.

### ISSUE THREAD

**Issue by nax1800** [Encryqed/Dumper-7#65]
I get 100+ errors when trying to build Fortnite's SDK (1.8, UE4.16). 
The errors are all the same, missing TSoftObjectPtr, missing TSoftClassPtr, etc...

What can I do to prevent this?
![image](https://github.com/Encryqed/Dumper-7/assets/74548019/fc3562f8-7b6c-4bb3-86ec-c950a5c2f6d6)

**Comment by Fischsalat** [comment]
use an older commit from september for now, I'm going to fix this on the rewrite branch
