### ISSUE TITLE
Crash when generating SDK for The Culling

### ISSUE THREAD

**Issue by Grovespaz** [Encryqed/Dumper-7#66]
When generating the SDK for The Culling (a defunct UE 4.15 game), the process suddenly exits during generation.
I can see a bunch of SDK files being generated (and they look very promising, digging out fields that no other SDK generator has found me thus far), but `SDK.hpp` is never generated.

I'm launching the game with EAC disabled.

I'm not entirely sure how to debug this properly because I don't know enough about how the SDK generator works yet. When attaching a debugger it breaks here:
![afbeelding](https://github.com/Encryqed/Dumper-7/assets/2829264/6067e5f7-0e39-40fd-8a51-936dd1b05a37)

```
Exception thrown at 0x00007FF921EEA8D6 (Dumper-7.dll) in Victory.exe: 0xC0000005: Access violation reading location 0x0000000000000008.
```

(I'm guessing it's actually GetFlags that's throwing the exception and it's getting inlined)

This is the call-stack:
![afbeelding](https://github.com/Encryqed/Dumper-7/assets/2829264/c63ab80d-11fe-4e80-adc7-488c494967aa)

(While I'm here, I might as well ask whether the moment of injection matters. Right now, I'm injecting the dll after the game has entirely loaded. I'm assuming it needs the entities loaded that I want to have in the SDK. Is that actually needed or can I inject the dll on process start already?)

**Comment by Fischsalat** [comment]
This is a strange error that I haven't seen before. Is there any place I can dowload the files for TheCulling?

Also, the point of injection matters, as you said, because some classes are just not loaded right after startup.

**Comment by Fischsalat** [comment]
Works

**Comment by Fischsalat** [comment]
This error occurred on other games too. It was caused by an invalid default object and has been fixed on the main branch.
