### ISSUE TITLE
TagAtLastTest was removed from SoftObjectPtr (TPersistentObjectPtr) in 5.3.2

### ISSUE THREAD

**Issue by gamerbross** [Encryqed/Dumper-7#67]
I'm not sure about the version it was removed exactly, but here is the commit epic removed it: https://github.com/EpicGames/UnrealEngine/commit/eb53ce238e6db965f38e6d0c14139267e462108b
I would like to do a PR but i don't think I would check if its existing correctly
(i struggled a lot trying to realize what was messing up the offsets)
I hope this gets fixed! 😀

**Comment by Fischsalat** [comment]
Wait, what the hell is "TagAtLastTest"?

I guess I don't need to remove anything if I've forgotten to add it in the first place.

**Comment by gamerbross** [comment]
I don't really know what is it, but its a property inside class TPersistentObjectPtr that is always adding to the SDK, and in 5.3.2 (not sure) it was removed, so it's breaking the offsets for classes that have a SoftObjectPtr property.
https://github.com/Encryqed/Dumper-7/blob/f38bec1a6eaa5b667011577e87bd3cf943f3e5cd/Dumper/Generator.cpp#L2160

**Comment by Fischsalat** [comment]
Oh, I guess it is in the SDK. Dementia, lovely.

I'll add a check for that based on the expected property size.

**Comment by Fischsalat** [comment]
Hi, any chance you know a (free) game that doesn't have `TagAtLastTest` anymore?

**Comment by Fischsalat** [comment]
Added a check for `TagAtLastTest` on the GeneratorRewrite branch. Main will soon be deprecated, so I don't see a need to add this check there.

I'll leave this issue open until GeneratorRewrite becomes the new main-branch, just in case someone has problems with TSoftObjectPtr.

**Comment by Fischsalat** [comment]
GeneratorRewrite replaced the main branch.
