### ISSUE TITLE
SDK Generation for Foxhole Crashes

### ISSUE THREAD

**Issue by 3216alec** [Encryqed/Dumper-7#69]
it seems to crash on StringifyObjectFlags in UnrealObjects.cpp

probably useless info but ill add it for context

i have tried using reclass and reversing all the major structs but the game seems quite different from the base 4.24 engine 
despite this using corrm's tool seems to generate a sdk mind you its missing alot but it seems to work using the base 4,24 structs
either this game is just fucked or i am just retarded and fell into a pitfall somewhere

**Comment by Fischsalat** [comment]
can you send the console output with of all the offsets?

**Comment by 3216alec** [comment]
sorry for the delay
```

Started Generation [Dumper-7]!

Dumper-7 by me, you & him


Searching for GObjects...

Found FChunkedFixedUObjectArray GObjects at offset 0x45eecb8

Found FName::AppendString at Offset 0x110bbf0

Off::UStruct::Children: 48
Off::UField::Next: 28
Off::UStruct::SuperStruct: 40
Off::UStruct::Size: 50
Off::UClass::CastFlags: b8
Off::UClass::ClassDefaultObject: f8
Off::UEnum::Names: 40
Off::UFunction::FunctionFlags: 98

Off::UFunction::ExecFunction: c0

Off::UProperty::ElementSize: 34
Off::UProperty::ArrayDim: 30
Off::UProperty::Offset_Internal: 44
Off::UProperty::PropertyFlags: 38
UPropertySize: 70

Off::UArrayProperty::Inner: 70
Off::USetProperty::ElementProp: 70
Off::UMapProperty::Base: 70

PE-Offset: 0x12cd6d0
PE-Index: 0x42

GameName: War
GameVersion: 4.24.3-0+++UE4+Release-4.24
```

**Comment by 3216alec** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/1337946/590f9357-a19a-44f4-847f-f7e9a9f25260)
