### ISSUE TITLE
SDK c++ struct Variables contains "-"

### ISSUE THREAD

**Issue by xsip** [Encryqed/Dumper-7#71]
Hi ! 
I dumped an sdk and it includes the "-" sign in variable names.
Can you tell me how to fix this?
![image](https://github.com/Encryqed/Dumper-7/assets/28891492/466df535-4295-472f-bd89-a1ac14699e63)

**Comment by Fischsalat** [comment]
It seems like I used `GetName()`instead of `GetValidName()`, so invalid characters weren't filtered out. Try the latest commit on main, I changed it.

**Comment by xsip** [comment]
Thx for fixing that!
Somehow i got another issue in another file.
This is my sdk output:
![image](https://github.com/Encryqed/Dumper-7/assets/28891492/d8551e35-b611-4ed8-97ff-d75ab27d3cd4)

**Comment by Fischsalat** [comment]
What a strange game you got there. I pushed yet another fix to the main branch. Tell me if it works!

**Comment by xsip** [comment]
It works fine now! Thanks for your great work!
