### ISSUE TITLE
Incorrect implementation of StaticClass for Blueprint classes 

### ISSUE THREAD

**Issue by KulaGGin** [Encryqed/Dumper-7#73]
At the moment current implementation to get the class is: 
```
class UClass* ABP_CharacterLightController_C::StaticClass()
{
	static class UClass* Clss = nullptr;

	if (!Clss)
		Clss = UObject::FindClassFast("BP_CharacterLightController_C");

	return Clss;
}
```

It is correct for C++ classes, because C++ classes get loaded at the start and never get unloaded from memory. However, blueprint classes might and do get loaded and then unloaded from memory when all objects of that class get destroyed. In my case it's on level load and unload.

So, when I first get the static class when I'm on the level, it works. But after levels get unloaded and then loaded back, the blueprint class has a different pointer and this pointer is no longer valid.

When I change the code to this:
```
class UClass* ABP_CharacterLightController_C::StaticClass()
{
	return UObject::FindClassFast("BP_CharacterLightController_C");
}
```

The bug disappears, because it always looks for the class.

For a quick fix, I did find and replace in the SDK project. Find: `(class UClass\* .BP_.*?::StaticClass\(\)\r\n{\r\n)(\s*static class UClass\* Clss = nullptr;\r\n)(.*?)(\s*if \(!Clss\)\r\n\s)(\s)` and replace with `$1$5UClass* `, this appears to fix all the BP classes in the project.

**Comment by Fischsalat** [comment]
Yea, I've seen that issue before and you're right, BlueprintGeneratedClasses need some fixes for `StaticClass`. 

I don't think finding the class every time without any caching is feasible, as most people use `StaticClass` per-tick to check object-types.

A solutions I was considering was to store the index rather than the pointer and verify the validity of the index of the class every time StaticClass is called. 

Pseudo-cpp:
```c++
class UClass* ABP_CharacterLightController_C::StaticClass()
{
	static int32 ClassIdx = 0x0;

	/* Could be external function, not really unique to this StaticClass functon */
	static auto SetClassIndex = [](UClass* Object, int32& Index) -> UClass*
	{
		if (Object)
			Index = Object->Index;

		return Object;
	};

	if (ClassIdx == 0x0)
		return SetClassIndex(UObject::FindClassFast("BP_CharacterLightController_C"), ClassIdx);

	UClass* ClassObj = static_cast<UClass*>(UObject::GObjects->GetByIndex(ClassIdx));

	/* Could use cast flags too to save some string comparisons */
	if (!ClassObj || ClassObj->GetName() != "BP_CharacterLightController_C")
		return SetClassIndex(UObject::FindClassFast("BP_CharacterLightController_C"), ClassIdx);

	return ClassObj;
}
```

**Comment by KulaGGin** [comment]
> A solutions I am considering is to store the index rather than the pointer and verify the validity of the index of the class every time StaticClass is called.
> ```c++
> class UClass* ABP_CharacterLightController_C::StaticClass()
> {
> 	static int32 ClassIdx = 0x0;
> 
> 	/* Could be external function, not really unique to this StaticClass functon */
> 	static auto SetClassIndex = [](UClass* Object, int32& Index) -> UClass*
> 	{
> 		if (Object)
> 			Index = Object->Index;
> 
> 		return Object;
> 	};
> ```
The problem with this is the class object can get destroyed at any point in time, and then once you try to access it, you might be accessing not accessible memory or just garbage memory.

When I was trying to figure out the bugs in the code, once the blueprint class actually gets loaded, the old class object would point to a different object, it wasn't even a class object. And I was just lucky that another object was put at the same memory location as the old class object, so I could get its' name without crashing.
Other times might not be that lucky and once you try to access Object->Index, you might be accessing either inaccessible memory or just garbage reallocated memory, so you can't just check if memory is accessible with IsBadReadPtr(Object): it will be accessible but something else is there now.

> I don't think finding the class every time without any caching is feasible, as most people use `StaticClass` per-tick to check object-types.

Well, that will be on programmers to cache and reset the pointers. I get the class only once at match start and then invalidate on match end, because that's when levels get loaded and unloaded, so it's always correct.

**Comment by Fischsalat** [comment]
> The problem with this is the class object can get destroyed at any point in time,

I am aware of this. In the proposed code above I'm explicitly **not** storing a `UClass*`, but rather the index of the class from the previous (re-)initialization. Re-fetching the Class from the index will return nullptr if the index was invalidated. If the index is still valid, but the object at said index was changed the check `ClassObj->GetName() != "BP_CharacterLightController_C")` fails and the object will be re-initialized.

**Comment by Fischsalat** [comment]
As you seemingly don't care about this issues anymore and it has been fixed, I'm going to close this.
