### ISSUE TITLE
Dumper crashes with "Heap corruption detected"

### ISSUE THREAD

**Issue by xsip** [Encryqed/Dumper-7#74]
Hi! I try to dump a game but somehow it crashes with the an heap corruption detected error.
Is this something fixable from your side/ something you know about?
![image](https://github.com/Encryqed/Dumper-7/assets/28891492/59da27fe-c5f4-45d7-9f25-f9a9c94b9a96)

Thx in advance!

**Comment by Fischsalat** [comment]
I don't know what causes that error, maybe it finds the wrong FName::AppendString offset or something else. I can't really do anything without the game name or any other information.

**Comment by xsip** [comment]
is it possible to contact you about game information/ to write it here for you to have a look and improve your dumper?
I would be able to give you my steam contact details to check out the game.

**Comment by Fischsalat** [comment]
you can send me a message on discord "fischsalat"
