### ISSUE TITLE
I am a beginner, I try to use the sdk and compile, there are a bunch of errors, can not pass the compilation

### ISSUE THREAD

**Issue by linwen1402** [Encryqed/Dumper-7#75]
![Uploading err.png…]()

**Comment by Fischsalat** [comment]
I have no ideas what these errors are. Undefined class or something? Can you send a screenshot with english errors, or a bit more explanation please?

**Comment by linwen1402** [comment]
> I have no ideas what these errors are. Undefined class or something? Can you send a screenshot with english errors, or a bit more explanation please?

yes,Undefined class

**Comment by linwen1402** [comment]
I don't know if I have a configuration error. Searching a lot of information on the Internet has not solved this problem

**Comment by Fischsalat** [comment]
Are all of your errors from the sdk itself, or do they come from **your** code?

**Comment by linwen1402** [comment]
> 你所有的错误都来自sdk本身，还是来自**你的**代码？

sdk

**Comment by Fischsalat** [comment]
ok, try the generator rewrite branch or try fixing them, with this little information I can't help you
