### ISSUE TITLE
Stuck at GNames

### ISSUE THREAD

**Issue by Saya-de** [Encryqed/Dumper-7#77]
Hello,
I need to use GNames, so far so good but its stuck after "Searching for GNames". I did a debug print and its able to find the correct GNames offset. After some more debugging i noticed its somewhere stuck inside "InitializeNamePool" and i have no idea how to fix that or what the issue is. 

Also i wonder when TMap is gonna get implemented if theres already a plan on that?
![image (4)](https://github.com/Encryqed/Dumper-7/assets/92759471/0c27a1d5-ac3e-43e4-9a10-9e1c12e8569f)

**Comment by Fischsalat** [comment]
What game are you stuck on, you can also try attaching visual studios debugger. 

For TMaps there are no concrete plans yet. But I'll definitively add it in the future.

**Comment by Saya-de** [comment]
I tried it on Dead by Daylight and need the GNames since i prefer them over AppendString 

> For TMaps there are no concrete plans yet. But I'll definitively add it in the future. 

Very nice ♥

**Comment by Fischsalat** [comment]
I don't really consider it to be an issue if GNames isn't found when AppendString **is** found. Why do you prefer GNames? Doesn't really matter, unless you're trying to hide from ac I guess.
