### ISSUE TITLE
gname cannot be found

### ISSUE THREAD

**Issue by dsafsgfdhf** [Encryqed/Dumper-7#86]
I didn't considerate the Generator: : Init () this function, you should be a void GeneratorRewrite: : InitEngineCore (), I'm looking for ue4.5.1, yet he cannot find gname, however, how to do it, you say should cover how to operate
/* manual override */
//ObjectArray::Init(/*GObjects*/, /*ChunkSize*/, /*bIsChunked*/);
//FName::Init(/*FName::AppendString*/);
//Off::InSDK::ProcessEvent::InitPE(/*PEIndex*/);

/* Back4Blood*/
//InitObjectArrayDecryption([](void* ObjPtr) -&gt;  uint8* { return reinterpret_cast&lt; uint8*&gt; (uint64(ObjPtr) ^ 0x8375);  });

/* Multiversus [Unsupported, weird GObjects-struct]*/
//InitObjectArrayDecryption([](void* ObjPtr) -&gt;  uint8* { return reinterpret_cast&lt; uint8*&gt; (uint64(ObjPtr) ^ 0x1B5DEAFD6B4068C);  });

ObjectArray::Init();
FName::Init();
Off::Init();
Off::InSDK::ProcessEvent::InitPE();  //Must be at this position, relies on offsets initialized in Off::Init()

Off::InSDK::Text::InitTextOffsets();  //Must be at this position, relies on offsets initialized in Off::InitPE()

InitSettings();

**Comment by dsafsgfdhf** [comment]
> 生成时有错误吗？如果找不到 GName，请使用 FName::AppendString 的偏移量覆盖 FName::Init

FName::AppendStringde How do I find the offset

**Comment by dsafsgfdhf** [comment]
> > 生成时有错误吗？如果找不到 GName，请使用 FName::AppendString 的偏移量覆盖 FName::Init
> 
> FName::AppendStringde 如何找到偏移量

	FName::Init(0x9A79100);是这样吗

**Comment by dsafsgfdhf** [comment]
> 生成时有错误吗？如果找不到 GName，请使用 FName::AppendString 的偏移量覆盖 FName::Init

i don't understand what you said about the operation of I coverage, can you explain it specifically, or add your discord

**Comment by Fischsalat** [comment]
You really need a better translator I can barely understand what you're talking about. You can find FName::AppendString just like any other offset using IDA. Look at the UnrealEngine sourc code.

**Comment by dsafsgfdhf** [comment]
I found out how to override the offset of FName::AppendString. Is FName::Init commented out

**Comment by Fischsalat** [comment]
Just add the offset to the existing FName::Init call `FName::Init(OFFSET)`. Like in in the [ReadMe](../blob/main/README.md#overriding-offsets)

**Comment by dsafsgfdhf** [comment]
Okay, thank you

**Comment by dsafsgfdhf** [comment]
FName::AppendString is also called gname

**Comment by Fischsalat** [comment]
no, it's not. GNames is TNameEntryArray/FNamePool. FName::AppendString is a function

**Comment by dsafsgfdhf** [comment]
okok

**Comment by dsafsgfdhf** [comment]
FName::Init(0x215D6D0);That's right?

**Comment by dsafsgfdhf** [comment]
![AF LW{4~}O2AO4D @4TW`$7](https://github.com/Encryqed/Dumper-7/assets/159912242/81a1e36a-dafa-4435-8c79-1421ebaa1170)It stopped at this point and then quit,
What is the reason,

**Comment by Fischsalat** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/fa2f9470-f807-4882-974f-a145fe1c4fcd)
property flags offset wasn't found, either overwrite it in Offsets.cpp or use CheatGear to dump ARK.
