### ISSUE TITLE
provide an example of an SDK?

### ISSUE THREAD

**Issue by elExample** [Encryqed/Dumper-7#89]
I used the Dump-7 storage SDK. And read UsingTheSDK.md. However, it is still impossible to create your own Hacker. DLL. I really hope you can provide a thread that uses the SDK. If you could provide the source code for reading, I would greatly appreciate it.

**Comment by Fischsalat** [comment]
UsingTheSDK literally contains everything you need, from project setup to calling functions. There's also a well documented example file at the bottom, so I think I explained it enough.
