### ISSUE TITLE
Wrong offset AnarchyWolfsLaw

### ISSUE THREAD

**Issue by quantumloader** [Encryqed/Dumper-7#90]
![image](https://github.com/Encryqed/Dumper-7/assets/131016951/40d537d5-44b4-4f40-8de2-262ab091cb93)

I'm new to this. What is this error? Is it related to the SDK or am I doing something wrong (Google translator)

**Comment by Fischsalat** [comment]
Что первая ошибка? Может быть, что первая ошибка вызвала больше ошибки. Пришли, пожалуйста, фото первой ошибки.

Не так хорошо говорю по-руски, но видел, что VisualStudio у тебя, по-руски, и хотел ответить по-руски. Извинти если ты не из россии, а из другой страны, каторая использует кирилический алфавит.

**Comment by quantumloader** [comment]
> Что первая ошибка? Может быть, что первая ошибка вызвала больше ошибки. Пришли, пожалуйста, фото первой ошибки.
> 
> Не так хорошо говорю по-руски, но видел, что VisualStudio у тебя, по-руски, и хотел ответить по-руски. Извинти если ты не из россии, а из другой страны, каторая использует кирилический алфавит.

You can write in English, I understand it. It will be easier for me to translate if I don't understand something.

The first mistake is also related to the offset

**Comment by Fischsalat** [comment]
Ok, sad, I just wanted to use my (limited) russian skills.

Ok, so what's the first error in the SDK? Can you send a picture of that?

**Comment by quantumloader** [comment]
> Ok, sad, I just wanted to use my (limited) russian skills.
> 
> Ok, so what's the first error in the SDK? Can you send a picture of that?

![image](https://github.com/Encryqed/Dumper-7/assets/131016951/3eb7cc4c-c904-4be3-b47f-f9d0ba343e45)

**Comment by Fischsalat** [comment]
hm, kinda expected some other error than just static_asserts. Could you send the SDK maybe?

**Comment by Fischsalat** [comment]
Ok, this is a stupid issue on my part. All you need to do to fix this is to change the `alignas(0x8)` to `alignas(0x1)` in Line 15 of PropertyFixup.hpp.

![image](https://github.com/Encryqed/Dumper-7/assets/64608145/75a27e10-dad1-4202-a9ff-4694d20d9cad)
