### ISSUE TITLE
Unresolved Symbols when compiling project with SDK

### ISSUE THREAD

**Issue by vznnnnn** [Encryqed/Dumper-7#91]
Added SDK files to project and cannot build due to unresolved symbols

![e9c0eb9b9cf16dd82759a41974cd772e](https://github.com/Encryqed/Dumper-7/assets/143833799/74effd62-6acb-4a67-a242-d33b80671e9f)

![89cb1229dc5090255b9f9a0f4d51d8be](https://github.com/Encryqed/Dumper-7/assets/143833799/b5d1827f-fac9-44b1-986b-8653f2bf9632)

**Comment by Fischsalat** [comment]
You didn't add CoreUObject_functions.cpp to your project.
