### ISSUE TITLE
"Static assertion failed" Wrong allignment/Offset

### ISSUE THREAD

**Issue by LionHackerman** [Encryqed/Dumper-7#92]
When dumping anygame. I get at 40+ of either Wrong alignment or wrong offset static assertion errors. I've tried using latest build and a previous version but they both produce the same result...

Game: Out Of Action
![image](https://github.com/Encryqed/Dumper-7/assets/58070003/89c55215-537a-406b-a807-60ce5afaae7e)

[OutOfActionUE4.27.zip](https://github.com/Encryqed/Dumper-7/files/14492562/OutOfActionUE4.27.zip)

**Comment by Fischsalat** [comment]
Windows.h unscoped macro/enum name strikes again!
Just rename OUT in Engine_structs.hpp line 13128.

![image](https://github.com/Encryqed/Dumper-7/assets/64608145/49ffd7c8-1456-4f74-b6ca-a13ec53f2ee9)
