### ISSUE TITLE
Fortnite 9.10 Issue

### ISSUE THREAD

**Issue by Vincent1232** [Encryqed/Dumper-7#94]
Hello, I am having a lot of issues with my SDK. Does anyone know how I can fix up my offsets?

![image](https://github.com/Encryqed/Dumper-7/assets/98626520/ef7bc976-3967-43ec-b2bc-8f0c76c4b8e8)

**Comment by clientinfo** [comment]
happens aswell when generating a payday 3 sdk and following the "how to use the sdk" guide provided in the readme.md

**Comment by Vincent1232** [comment]
> happens aswell when generating a payday 3 sdk and following the "how to use the sdk" guide provided in the readme.md

I already use the guide.

**Comment by Fischsalat** [comment]
Literally just set this to "build only".
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/cb998843-3838-4f78-9e5f-24416a3c10d3)

**Comment by clientinfo** [comment]
using the example code you provided in your sdk guide

**Comment by clientinfo** [comment]
[4.27.2-0+++UE4+Release-4.27-PAYDAY3.zip](https://github.com/Encryqed/Dumper-7/files/14510346/4.27.2-0%2B%2B%2BUE4%2BRelease-4.27-PAYDAY3.zip)
maybe it help providing the sdk, in my case its payday 3

**Comment by Fischsalat** [comment]
I accidentally removed FName from the SDK for a few hours yesterday. It's back already, just re-dump.

**Comment by clientinfo** [comment]
![image](https://github.com/Encryqed/Dumper-7/assets/85733422/6bd7cc40-6064-4247-be85-44e9f64f3e96)
![image](https://github.com/Encryqed/Dumper-7/assets/85733422/79f6656f-ab46-48c9-b30c-d3a823928b12)
![image](https://github.com/Encryqed/Dumper-7/assets/85733422/e3b76bc3-88c3-418c-9f9b-6c40989cb32e)
![image](https://github.com/Encryqed/Dumper-7/assets/85733422/fa2fd6db-ab59-466d-87e8-0844c2589432)
[4.27.2-0+++UE4+Release-4.27-PAYDAY3.zip](https://github.com/Encryqed/Dumper-7/files/14511462/4.27.2-0%2B%2B%2BUE4%2BRelease-4.27-PAYDAY3.zip)

yea something is odd again

**Comment by Vincent1232** [comment]
> ![image](https://private-user-images.githubusercontent.com/85733422/310542280-6bd7cc40-6064-4247-be85-44e9f64f3e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY3NDksIm5iZiI6MTcwOTc3NjQ0OSwicGF0aCI6Ii84NTczMzQyMi8zMTA1NDIyODAtNmJkN2NjNDAtNjA2NC00MjQ3LWJlODUtNDRlOWY2NGYzZTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZjU3ZjRjYjJmN2QwZTRlNGFiYzkyMWExZjU5NDk5Y2ZmN2I5ZGQ5OGNkYTViNTBkNTM0NjllYTA4YTAxNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JxVjy0nM-avf0IpMZhXpfj6bGq76oAhBcVHsQ7lEkY) ![image](https://private-user-images.githubusercontent.com/85733422/310542369-79f6656f-ab46-48c9-b30c-d3a823928b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY3NDksIm5iZiI6MTcwOTc3NjQ0OSwicGF0aCI6Ii84NTczMzQyMi8zMTA1NDIzNjktNzlmNjY1NmYtYWI0Ni00OGM5LWIzMGMtZDNhODIzOTI4YjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjY3MzY1ZmQ0MDg0NGYwYmUzODI0YWZkNTZiMGNlYTczMzMwNWYxZTUzZjMxMWQ3YWM5MDcwZjgxMzhmODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RDHqbCwRzo93LiTfKAV1Cfti_12vfszN7cLZ-6ToPg) ![image](https://private-user-images.githubusercontent.com/85733422/310542440-e3b76bc3-88c3-418c-9f9b-6c40989cb32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY3NDksIm5iZiI6MTcwOTc3NjQ0OSwicGF0aCI6Ii84NTczMzQyMi8zMTA1NDI0NDAtZTNiNzZiYzMtODhjMy00MThjLTlmOWItNmM0MDk4OWNiMzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWRkY2I3OGZmYTAzZjk4MGQyNGMwMDhhMWJjNTU5MTUwMmJhODJjNzNhYTYwYzNmMDM3OGViYTI2MTdmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bE6tRl2GXLYdmgeSNfoDK2sNG7tn8eIHStwrGJpuMGI) ![image](https://private-user-images.githubusercontent.com/85733422/310542526-fa2fd6db-ab59-466d-87e8-0844c2589432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzY3NDksIm5iZiI6MTcwOTc3NjQ0OSwicGF0aCI6Ii84NTczMzQyMi8zMTA1NDI1MjYtZmEyZmQ2ZGItYWI1OS00NjZkLTg3ZTgtMDg0NGMyNTg5NDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxNTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NjA0Y2JlMGQ1NzhiMjU3ZGQ2NTNmNTIxZDY4YmVmMjYzZDU5YjQ1ZTZmN2E3Mzg5MTliMTg5ZThlNjA0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5TL7lE5SQJi23ez4WpDJJehTxwwe2wOzwBHdwDQFCA) [4.27.2-0+++UE4+Release-4.27-PAYDAY3.zip](https://github.com/Encryqed/Dumper-7/files/14511462/4.27.2-0%2B%2B%2BUE4%2BRelease-4.27-PAYDAY3.zip)
> 
> yea something is odd again

Same issue

**Comment by faizkot** [comment]
![image_2024-03-07_120523401](https://github.com/Encryqed/Dumper-7/assets/110542646/1a2cc706-a409-4072-b6dc-f87c85cbc54f)
any idea on this??

**Comment by TimmieDevelops** [comment]
> ![image_2024-03-07_120523401](https://github.com/Encryqed/Dumper-7/assets/110542646/1a2cc706-a409-4072-b6dc-f87c85cbc54f)
> 
> any idea on this??

You need to download stddef.h

**Comment by faizkot** [comment]
> > ![image_2024-03-07_120523401](https://private-user-images.githubusercontent.com/110542646/310742551-1a2cc706-a409-4072-b6dc-f87c85cbc54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODQ4NzQsIm5iZiI6MTcwOTc4NDU3NCwicGF0aCI6Ii8xMTA1NDI2NDYvMzEwNzQyNTUxLTFhMmNjNzA2LWE0MDktNDA3Mi1iNmRjLWY4N2M4NWNiYzU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNDA5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjBmOTkxOTQ3MjhjZTkxMTAzMjdjZDBmYWI3MThhMTZkNmU4MDJjZDNkYzRlZDIwMjE0ZjgwNmYxMmNkOWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aVA7z3kg0-zLvyrbtGJNcP6K2qTh39Dc0afVt4HGDk0)
> > any idea on this??
> 
> You need to download stddef.h.

where tho??

**Comment by Vincent1232** [comment]
> > > ![image_2024-03-07_120523401](https://private-user-images.githubusercontent.com/110542646/310742551-1a2cc706-a409-4072-b6dc-f87c85cbc54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODQ4NzQsIm5iZiI6MTcwOTc4NDU3NCwicGF0aCI6Ii8xMTA1NDI2NDYvMzEwNzQyNTUxLTFhMmNjNzA2LWE0MDktNDA3Mi1iNmRjLWY4N2M4NWNiYzU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNDA5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjBmOTkxOTQ3MjhjZTkxMTAzMjdjZDBmYWI3MThhMTZkNmU4MDJjZDNkYzRlZDIwMjE0ZjgwNmYxMmNkOWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aVA7z3kg0-zLvyrbtGJNcP6K2qTh39Dc0afVt4HGDk0)
> > > any idea on this??
> > 
> > 
> > You need to download stddef.h.
> 
> where tho??

On the website, you have to look up where to find them.

**Comment by TimmieDevelops** [comment]
> > > ![image_2024-03-07_120523401](https://private-user-images.githubusercontent.com/110542646/310742551-1a2cc706-a409-4072-b6dc-f87c85cbc54f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODQ4NzQsIm5iZiI6MTcwOTc4NDU3NCwicGF0aCI6Ii8xMTA1NDI2NDYvMzEwNzQyNTUxLTFhMmNjNzA2LWE0MDktNDA3Mi1iNmRjLWY4N2M4NWNiYzU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNDA5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjBmOTkxOTQ3MjhjZTkxMTAzMjdjZDBmYWI3MThhMTZkNmU4MDJjZDNkYzRlZDIwMjE0ZjgwNmYxMmNkOWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aVA7z3kg0-zLvyrbtGJNcP6K2qTh39Dc0afVt4HGDk0)
> > > any idea on this??
> > 
> > 
> > You need to download stddef.h.
> 
> where tho??

On the website, you have to look up where to find them.

**Comment by Fischsalat** [comment]
> well shit ![image](https://private-user-images.githubusercontent.com/85733422/310510641-dc66dbe8-ecff-44a3-95e1-64f49fa7da4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDYwNjQsIm5iZiI6MTcwOTg0NTc2NCwicGF0aCI6Ii84NTczMzQyMi8zMTA1MTA2NDEtZGM2NmRiZTgtZWNmZi00NGEzLTk1ZTEtNjRmNDlmYTdkYTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIxMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzBlMDVhN2Y2MmQ2ODA3ODdjZTJkOGI4YjQwMDQ5MjU3YmVjOTE3ZDEzNTk3YTkxNzkxNzJkNGEzZTQxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5fzPc2Kbz1ph1U6qQwtUlHcc5za1lbMumRYdM8S8rbc)

As I said, I accidentally removed FName from the SDK, hence the errors. GET THE LATEST COMMIT AND REDUMP.

**Comment by LionHackerman** [comment]
> > well shit ![image](https://private-user-images.githubusercontent.com/85733422/310510641-dc66dbe8-ecff-44a3-95e1-64f49fa7da4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDYwNjQsIm5iZiI6MTcwOTg0NTc2NCwicGF0aCI6Ii84NTczMzQyMi8zMTA1MTA2NDEtZGM2NmRiZTgtZWNmZi00NGEzLTk1ZTEtNjRmNDlmYTdkYTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIxMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzBlMDVhN2Y2MmQ2ODA3ODdjZTJkOGI4YjQwMDQ5MjU3YmVjOTE3ZDEzNTk3YTkxNzkxNzJkNGEzZTQxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5fzPc2Kbz1ph1U6qQwtUlHcc5za1lbMumRYdM8S8rbc)
> 
> As I said, I accidentally removed FName from the SDK, hence the errors. GET THE LATEST COMMIT AND REDUMP.

New build doesn't work..... You broke it 

![image](https://github.com/Encryqed/Dumper-7/assets/58070003/09b26c5b-2bbc-4722-911a-fec677f74da4)

**Comment by Fischsalat** [comment]
YoU bRokE iT!!!
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/1d70a331-145c-4fa2-b67a-c3c221f74221)
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/b9fd0833-998e-4204-aae4-618d7da53c99)

**Comment by Vincent1232** [comment]
No wonder this dumper is fuck and shit💀 💀 💀
