### ISSUE TITLE
Error with SDK::InitGObjects()

### ISSUE THREAD

**Issue by quantumloader** [Encryqed/Dumper-7#96]
![image](https://github.com/Encryqed/Dumper-7/assets/131016951/c369c6f5-6744-451d-8d3a-22663b3768c1)
![image](https://github.com/Encryqed/Dumper-7/assets/131016951/44c4ba92-d143-4a81-abaa-03eb4d9ebba5)

I don't understand what I'm doing wrong. I'm new to this. But I don't understand why he doesn't want to show up. The SDK is connected

**Comment by Fischsalat** [comment]
InitGObjects() no longer exists, read the changelog.
