### ISSUE TITLE
Wrong offsets and size

### ISSUE THREAD

**Issue by HeywoodJahblome** [Encryqed/Dumper-7#97]
I dumped a game and I'm getting loads of asserts for UPrimitiveComponent and other classes that inherit it. USceneComponent that UPrimitiveComponent inherits from seems fine, but the size of the class is larger than the offset for the first field in UPrimitiveComponent, which doesn't seem like it should be the case. I'm not sure if its the struct has been modified in the engine for the game, as I'm still trying to learn how to mod ue games.

Also I'm not sure if it has to do with the dumper or the game but EClassFlags was throwing an error because it was an int but needed to be a uint32_t.

![Screenshot_1](https://github.com/Encryqed/Dumper-7/assets/162904026/b69bb2cb-39ec-424f-8a03-59b2c4102d24)
![Screenshot_2](https://github.com/Encryqed/Dumper-7/assets/162904026/c1a1e829-4128-45ca-8cf2-e57a12f42f35)
![Screenshot_3](https://github.com/Encryqed/Dumper-7/assets/162904026/9b36e629-c57a-4de0-850a-ced99004d11d)

**Comment by Fischsalat** [comment]
Congratulations, you're just sending me absolutely useless information. Why bother reading the issues part of the readme when you can just open an issue and send screenshots of useless intellisense errors?
\
Feel free to make an issue if you have **actual** problems.
\
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/f79004d4-a7c9-4b8a-8019-62362dea378d)

**Comment by HeywoodJahblome** [comment]
I apologize, you're right, I thought they were build errors as they only showed up once it failed to build. I didn't think twice about it, since I usually have it set to build only.
