### ISSUE TITLE
Wrong variable type?

### ISSUE THREAD

**Issue by gamerbross** [Encryqed/Dumper-7#98]
https://github.com/Encryqed/Dumper-7/blob/main/Dumper/CppGenerator.cpp#L5196
![image](https://github.com/Encryqed/Dumper-7/assets/55158797/ba48cfa7-be64-47fb-825b-4a4619305d46)
Shouldn't be the type of `Value` the same as `Key`?

**Comment by Fischsalat** [comment]
It shouldn't be value, I wanted the Equals function to receive two keys to check for quality. 

Thanks for pointing out my strange mistakes. Changed it to this:
![image](https://github.com/Encryqed/Dumper-7/assets/64608145/c330700b-eac7-43ed-b6ec-48acb5da0f7c)
